### ISSUE TITLE
Test failures with ElementTree and demo if docutils is absent

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1005]
The following errors ~are not seen in Python 3.6 but they occur while running the test suite with Python 3.8~ (Edited: The error occured if `docutils` is not in the environment):
```
======================================================================
ERROR: test_description_use_css (traitsui.extras.tests.test_demo.TestDemoPathDescription)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/.edm/envs/traitsui-7.0.1-release/lib/python3.6/site-packages/traitsui/extras/tests/test_demo.py", line 64, in test_description_use_css
    tree = ET.fromstring(model.description)
  File "/Users/kchoi/.edm/envs/traitsui-7.0.1-release/lib/python3.6/xml/etree/ElementTree.py", line 1315, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

======================================================================
ERROR: test_description_with_empty_directory (traitsui.extras.tests.test_demo.TestDemoPathDescription)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/.edm/envs/traitsui-7.0.1-release/lib/python3.6/site-packages/traitsui/extras/tests/test_demo.py", line 38, in test_description_with_empty_directory
    tree = ET.fromstring(model.description)
  File "/Users/kchoi/.edm/envs/traitsui-7.0.1-release/lib/python3.6/xml/etree/ElementTree.py", line 1315, in XML
    return parser.close()
  File "<string>", line None
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

======================================================================
ERROR: test_use_index_rst (traitsui.extras.tests.test_demo.TestDemoPathDescription)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/.edm/envs/traitsui-7.0.1-release/lib/python3.6/site-packages/traitsui/extras/tests/test_demo.py", line 53, in test_use_index_rst
    tree = ET.fromstring(model.description)
  File "/Users/kchoi/.edm/envs/traitsui-7.0.1-release/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

**Comment by kitchoi** [comment]
These tests were run with `7.0.1` release. Since then the `test_demo` module has been moved to `ets-demo` distribution.

**Comment by kitchoi** [comment]
Sorry, the environment was actually created on Python 3.6.
Not sure why we are not seeing this on CI.
Correcting the title.

**Comment by kitchoi** [comment]
My bad... I needed to install `docutils` in my environment. Without docutils, the rsT wasn't rendered into something that XML parser can read. Sorry for the noise.

**Comment by kitchoi** [comment]
The errors are quite obscure though, which caused us some time to debug. 
Ideally the test should be skipped if the `docutils` is an optional dependency, or the application should provide more information about missing `docutils` (so at least one gets to see it while running the tests).

**Comment by kitchoi** [comment]
Closing again: Since the issue was opened, the `etsdemo` has been extracted to its own distribution. With that, `docutils` is no longer an optional dependency but a required dependency. The obscure test error message should not happen again.
