### ISSUE TITLE
Errors in doc examples

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1051]
This issue relates to the example code found in
tutorials - https://github.com/enthought/traitsui/tree/master/examples
(a sub-issue of #1027 )

When I run the tree_editor.py file everything runs fine, but if I click on an employees name, and then click in any textbook I get the error:
```
$ python tree_editor.py 
Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/general-use/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 338, in sizeHint
    if ui.view.width > 0:
AttributeError: 'NoneType' object has no attribute 'width'
Abort trap: 6
```

Also, initially when I ran view_standalone.py, view_multi_object.py, and wizard.py the window closed immediately.  Quickly realized this was because I needed to specify the toolkit with 
```
from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'wx'
```
Should these lines be included in the wx files because traitsui defaults to trying PyQt4 first?  It is probably unnecessary, but just a thought.  Also, when these files are run, I get strange output (this has been noticed before - see Pr #1044 )
```
$ python view_multi_object.py 
09:22:04 AM: Debug: Adding duplicate image handler for 'PNG file'
09:22:04 AM: Debug: Adding duplicate image handler for 'JPEG file'
09:22:04 AM: Debug: Adding duplicate image handler for 'TIFF file'
09:22:04 AM: Debug: Adding duplicate image handler for 'GIF file'
09:22:04 AM: Debug: Adding duplicate image handler for 'PNM file'
09:22:04 AM: Debug: Adding duplicate image handler for 'PCX file'
09:22:04 AM: Debug: Adding duplicate image handler for 'IFF file'
09:22:04 AM: Debug: Adding duplicate image handler for 'Windows icon file'
09:22:04 AM: Debug: Adding duplicate image handler for 'Windows cursor file'
09:22:04 AM: Debug: Adding duplicate image handler for 'Windows animated cursor file'
09:22:04 AM: Debug: Adding duplicate image handler for 'TGA file'
09:22:04 AM: Debug: Adding duplicate image handler for 'XPM file'
09:22:04 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
09:22:04 AM: Debug: Adding duplicate animation handler for '1' type
09:22:04 AM: Debug: Adding duplicate animation handler for '2' type
09:22:04 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
09:22:04 AM: Debug: Adding duplicate animation handler for '1' type
09:22:04 AM: Debug: Adding duplicate animation handler for '2' type
09:22:04 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
09:22:04 AM: Debug: Adding duplicate animation handler for '1' type
09:22:04 AM: Debug: Adding duplicate animation handler for '2' type

python view_standalone.py 
09:33:58 AM: Debug: Adding duplicate image handler for 'PNG file'
09:33:58 AM: Debug: Adding duplicate image handler for 'JPEG file'
09:33:58 AM: Debug: Adding duplicate image handler for 'TIFF file'
09:33:58 AM: Debug: Adding duplicate image handler for 'GIF file'
09:33:58 AM: Debug: Adding duplicate image handler for 'PNM file'
09:33:58 AM: Debug: Adding duplicate image handler for 'PCX file'
09:33:58 AM: Debug: Adding duplicate image handler for 'IFF file'
09:33:58 AM: Debug: Adding duplicate image handler for 'Windows icon file'
09:33:58 AM: Debug: Adding duplicate image handler for 'Windows cursor file'
09:33:58 AM: Debug: Adding duplicate image handler for 'Windows animated cursor file'
09:33:58 AM: Debug: Adding duplicate image handler for 'TGA file'
09:33:58 AM: Debug: Adding duplicate image handler for 'XPM file'
```

Also, when running the wizard.py I see 
```
$ python wizard.py 
09:35:13 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
09:35:13 AM: Debug: Adding duplicate animation handler for '1' type
09:35:13 AM: Debug: Adding duplicate animation handler for '2' type
09:35:13 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
09:35:13 AM: Debug: Adding duplicate animation handler for '1' type
09:35:13 AM: Debug: Adding duplicate animation handler for '2' type
09:35:13 AM: Debug: Adding duplicate image handler for 'Windows bitmap file'
09:35:13 AM: Debug: Adding duplicate animation handler for '1' type
09:35:13 AM: Debug: Adding duplicate animation handler for '2' type
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/wincmn.cpp(475) in ~wxWindowBase(): any pushed event handlers must have been removed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/general-use/lib/python3.6/site-packages/traitsui/wx/view_application.py", line 152, in OnInit
    args=self.args,
  File "/Users/aayres/.edm/envs/general-use/lib/python3.6/site-packages/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/Users/aayres/.edm/envs/general-use/lib/python3.6/site-packages/traitsui/ui.py", line 246, in ui
    self.rebuild(self, parent)
SystemError: PyEval_EvalFrameEx returned a result with an error set
OnInit returned false, exiting...
```

Also, there is a bit of mismatch between the code files in this directory, and the examples given in the traitsui user manual. 
Example 1 in the manual explicitly references a file configure_traits.py which does not exist in the directory.  Similarly examples 5b references default_traits_view2.py which is not in the directory. Additionally, the directory contains files view_standalone.py, view_multi_object.py, view_attributes.py, and include_extra.py which are not mentioned in the user manual.  

I noticed that in the user manual the example numbers randomly jump from 9 to 12 (there is no example 10 or 11).  

In example 15 in the manual the last line of code from the file enum_editor.py is missing. 

Additionally, some docstrings for files don't line up with the intended new content being shown by that example.

**Comment by aaronayres35** [comment]
I was unable to recreate the tutor.py issues I was seeing before.  I opened a trivial PR to add the missing line of code for example 15.  For the example numbering, it seems there is an image named ui_for_ex12.jpg and similarly for the some of the later examples.  Im assuming this is why they weren't renumbered.  
I couldn't figure out the tree_editor issue, but the error only occurs when the application is closed, so a user can still see and interact with it as they're supposed to.

**Comment by kitchoi** [comment]
The attribute error in tree_editor.py is related to #1145, I think.

**Comment by aaronayres35** [comment]
first bullet was fixed by #1286
