### ISSUE TITLE
CompoundEditor_demo.py segfault on qt

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1073]
It is possible this is the expected behavior but I was confused.

When using Qt, if you click for example 'C' in the custom section, and then in the text section try to input an integer error messages pop up and when you close them it seg faults.  
On wx however, you simply get the pop ups giving a value error, but the GUI doesn't close and there is no segfault. Once you manual close it, there is an error in the command line namely 
```
$ python CompoundEditor_demo.py 
03:35:06 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
03:35:06 PM: Debug: Adding duplicate animation handler for '1' type
03:35:06 PM: Debug: Adding duplicate animation handler for '2' type
03:35:06 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
03:35:06 PM: Debug: Adding duplicate animation handler for '1' type
03:35:06 PM: Debug: Adding duplicate animation handler for '2' type
03:35:06 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
03:35:06 PM: Debug: Adding duplicate animation handler for '1' type
03:35:06 PM: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/Users/aayres/Desktop/traitsui/traitsui/wx/editor_factory.py", line 125, in update_object
    self.value = self.control.GetValue()
AttributeError: 'NoneType' object has no attribute 'GetValue'
```

**Comment by kitchoi** [comment]
> On wx however, you simply get the pop ups giving a value error, but the GUI doesn't close and there is no segfault. Once you manual close it, there is an error in the command line namely

If I added some print functions in `traitsui.wx.editor_factory.TextEditor.update_object`:
```

    def update_object(self, event):
        """ Handles the user changing the contents of the edit control.
        """
        print("entering", event)
        if isinstance(event, wx.FocusEvent):
            event.Skip()
        try:
            self.value = self.control.GetValue()
        except TraitError as excp:
            pass
        print("exiting", event)
```
When I type an invalid value in the textbox, then I see this in the console:
```
entering <wx._core.CommandEvent object at 0x7fee9cf41948>
entering <wx._core.FocusEvent object at 0x7fee9cf4faf8>
```
When I then press OK on the dialog showing the validation error, a second dialog popups, and at that time, this turns up in the console:
```
exiting <wx._core.FocusEvent object at 0x7fee9cf4faf8>
```
When I then press OK on the second dialog, this additional print turns up:
```
exiting <wx._core.CommandEvent object at 0x7fee9cf41948>
```
When I manually closes the UI window (while the text in the textbox is still invalid), I get these:
```
entering <wx._core.FocusEvent object at 0x7fee9ea1fd38>
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/wx/editor_factory.py", line 126, in update_object
    self.value = self.control.GetValue()
AttributeError: 'NoneType' object has no attribute 'GetValue'
```

**Comment by aaronayres35** [comment]
The wx issue is fixed by #1286.  I still see the Qt segfault though.  Also another thing to note, on Qt when you enter an integer you get 2 dialogs popping up with the error and you can not click the 'okay' button on either.  I had to close the dialogs and segfault occurs right on the close

**Comment by kitchoi** [comment]
For reference, I think the wx part of this issue was already fixed by #1161, which was merged earlier. I am sorry I should have updated this issue when #1161 was merged.
