### ISSUE TITLE
SetEditor_demo.py wx problems

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1074]
It seems issues with this demo are already known and are mentioned in issue #913 .
However this issue specifies problems when using PyQt4.

When I run with Wx I immediately see:
<details>

```
$ python SetEditor_demo.py 
03:49:41 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
03:49:41 PM: Debug: Adding duplicate animation handler for '1' type
03:49:41 PM: Debug: Adding duplicate animation handler for '2' type
03:49:41 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
03:49:41 PM: Debug: Adding duplicate animation handler for '1' type
03:49:41 PM: Debug: Adding duplicate animation handler for '2' type
03:49:41 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'
03:49:41 PM: Debug: Adding duplicate animation handler for '1' type
03:49:41 PM: Debug: Adding duplicate animation handler for '2' type
Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_window.py", line 491, in _paint
    sizer.Draw(self.control)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 4217, in Draw
    self._contents.draw(set_standard_font(wx.PaintDC(window)))
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 3495, in draw
    item.draw(dc)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 2682, in draw
    self.end_draw(dc)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 638, in end_draw
    dc.SetClippingRegion(*self._save_clip)
TypeError: DC.SetClippingRegion(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'bool'
  overload 3: argument 1 has unexpected type 'bool'
Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_window.py", line 491, in _paint
    sizer.Draw(self.control)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 4217, in Draw
    self._contents.draw(set_standard_font(wx.PaintDC(window)))
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 3495, in draw
    item.draw(dc)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 2682, in draw
    self.end_draw(dc)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 638, in end_draw
    dc.SetClippingRegion(*self._save_clip)
TypeError: DC.SetClippingRegion(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'bool'
  overload 3: argument 1 has unexpected type 'bool'
Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_window.py", line 491, in _paint
    sizer.Draw(self.control)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 4217, in Draw
    self._contents.draw(set_standard_font(wx.PaintDC(window)))
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 3495, in draw
    item.draw(dc)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 2682, in draw
    self.end_draw(dc)
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/site-packages/pyface/dock/dock_sizer.py", line 638, in end_draw
    dc.SetClippingRegion(*self._save_clip)
TypeError: DC.SetClippingRegion(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'bool'
  overload 3: argument 1 has unexpected type 'bool'
``` 

</details>
in the command line.

**Comment by ievacerny** [comment]
Drive by comment - the problem seems to be coming from pyface and is affecting other demos as well: https://github.com/enthought/pyface/issues/558
