### ISSUE TITLE
List(Directory(exists=True)) causes Aborted (core dumped)

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#1154]
I notice this using traits v6.1.1 and traitsui v7.0.1 on Ubuntu. I have not checked other platforms.

Here is code to reproduce:
```python
from traits.api import Directory, HasTraits, List

class Foo(HasTraits):
    dirs = List(Directory(exists=True))

Foo().configure_traits()
```
Triggering the 'Add' action from the list editor hamburger menu causes an abort.

**Comment by rahulporuri** [comment]
I am able to reproduce this from a windows 10 machine from the traitsui-test-3.6-pyqt5 environment. See below the dialog that pops up and the traceback on the commandline.

![image](https://user-images.githubusercontent.com/1926457/90863161-1d965f80-e37e-11ea-89a7-11ef14db548c.png)

```
>>> from traits.api import *
>>> class Foo(HasTraits):
...     dirs = List(Directory(exists=True))
...
>>> Foo().configure_traits()
Traceback (most recent call last):
File "<string>", line 2, in handler
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\list_editor.py", line 321, in add_empty
self.add_item(0)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\list_editor.py", line 304, in add_item
self.value = list[:index] + [value] + list[index:]
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\editor.py", line 755, in _set_value
self.ui.do_undoable(self.__set_value, value)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\ui.py", line 656, in do_undoable
action(*args, **kw)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\editor.py", line 689, in __set_value
method(self.ui.info, self.object, name, value)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\handler.py", line 286, in setattr
setattr(object, name, value)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\trait_types.py", line 2473, in validate
return TraitListObject(self, object, name, value)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\trait_list_object.py", line 582, in __init__
notifiers=[self.notifier],
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\trait_list_object.py", line 210, in __init__
super().__init__(self.item_validator(item) for item in iterable)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\trait_list_object.py", line 210, in <genexpr>
super().__init__(self.item_validator(item) for item in iterable)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\trait_list_object.py", line 862, in _item_validator
return trait_validator(object, self.name, value)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\trait_types.py", line 1511, in validate
self.error(object, name, value)
File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\base_trait_handler.py", line 75, in error
object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'dirs' trait of a Foo instance must be a directory name or an object implementing the os.PathLike interface, but a value of '' <class 'str'> was specified.
```

**Comment by corranwebster** [comment]
Adding to a comment from #1559 here.

Avoiding the hard crash is only half of the solution.  If the default value is bad, then we still have the problem that the user can't add a value without getting a pop-up that they can't do anything to fix.  If the developer of the UI doesn't control the code with the trait definition, then things can get very convoluted to fix.

We should add a `default_factory` trait that allows the UI developer to specify a valid default value via a callable.  If this is not `None`, we should prefer it over the default value provided by the trait.

This potentially has additional advantages and uses, but in the short-term provides the complete solution to the problem.
