### ISSUE TITLE
Test failures on TextEditor for Wx on Windows

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1177]
On Windows, we are currently seeing these new test failures for Wx:
```
======================================================================
FAIL: test_custom_auto_set_false_do_not_update_wx (traitsui.tests.editors.test_text_editor.TestTextEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_text_editor.py", line 278, in test_custom_auto_set_false_do_not_update_wx
    self.assertEqual(display_name, "NEW")
AssertionError: '' != 'NEW'
+ NEW
======================================================================
FAIL: test_custom_auto_set_true_update_text (traitsui.tests.editors.test_text_editor.TestTextEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_text_editor.py", line 236, in test_custom_auto_set_true_update_text
    name_field.perform(command.KeySequence("NEW"))
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traits\testing\unittest_tools.py", line 119, in __exit__
    raise self.failureException(msg.format(*items))
AssertionError: Change event for name was fired 0 times instead of 3
======================================================================
FAIL: test_simple_auto_set_false_do_not_update_wx (traitsui.tests.editors.test_text_editor.TestTextEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_text_editor.py", line 222, in test_simple_auto_set_false_do_not_update_wx
    self.assertEqual(display_name, "NEW")
AssertionError: '' != 'NEW'
+ NEW
======================================================================
FAIL: test_simple_auto_set_update_text (traitsui.tests.editors.test_text_editor.TestTextEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_text_editor.py", line 172, in test_simple_auto_set_update_text
    name_field.perform(command.KeySequence("NEW"))
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traits\testing\unittest_tools.py", line 119, in __exit__
    raise self.failureException(msg.format(*items))
AssertionError: Change event for name was fired 0 times instead of 3
```

See e.g. https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/34905040/job/5h5vwkxaunujxo84

**Comment by kitchoi** [comment]
These failures from `test_helpers` might be related:
```
======================================================================
FAIL: test_key_click (traitsui.testing.tester.wx.tests.test_helpers.TestInteractions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\testing\tester\wx\tests\test_helpers.py", line 87, in test_key_click
    self.assertEqual(textbox.Value, "A")
AssertionError: '' != 'A'
+ A
======================================================================
FAIL: test_key_sequence (traitsui.testing.tester.wx.tests.test_helpers.TestInteractions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\testing\tester\wx\tests\test_helpers.py", line 72, in test_key_sequence
    self.assertEqual(textbox.Value, "abc")
AssertionError: '' != 'abc'
+ abc
```
See build on https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/34968131/job/js7ewpm1b62puxa1 from #1176

**Comment by kitchoi** [comment]
Edited title: Confirmed this is only seen on Windows.

**Comment by kitchoi** [comment]
> These failures from test_helpers might be related:

The test failure for `test_key_click` isn't. That one is now a separate issue: #1183
