### ISSUE TITLE
UI Tester import side effect Test failure when run locally on wx - does not occur on CI

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1260]
Running the following code generated the test error:
```
$ python etstool.py install --toolkit=wx --environment=wx-env-new
$ edm shell -e wx-env-new
$ cd traitsui/testing
$ python -m unittest
```

and the subsequent error:

<details>

```
======================================================================
ERROR: tester.qt4.tests.test_helpers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tester.qt4.tests.test_helpers
Traceback (most recent call last):
  File "/Users/aayres/.edm/envs/wx-env-new/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/aayres/.edm/envs/wx-env-new/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/Users/aayres/Desktop/traitsui/traitsui/testing/tester/qt4/tests/test_helpers.py", line 22, in <module>
    from traitsui.testing.tester.qt4 import _interaction_helpers
  File "/Users/aayres/.edm/envs/wx-env-new/lib/python3.6/site-packages/traitsui/testing/tester/qt4/_interaction_helpers.py", line 11, in <module>
    from pyface.qt import QtCore, QtGui
  File "/Users/aayres/.edm/envs/wx-env-new/lib/python3.6/site-packages/pyface/qt/__init__.py", line 83, in <module>
    raise ImportError("Cannot import PySide, PySide2, PyQt5 or PyQt4")
ImportError: Cannot import PySide, PySide2, PyQt5 or PyQt4


----------------------------------------------------------------------
```
</details>

**Comment by kitchoi** [comment]
The Qt tests are skipped in a Wx environment via the following setup in CI because CI is running tests using discover and setting an environment variable:

https://github.com/enthought/traitsui/blob/b7b6037810fdc9aa6d52a016ec46444e0027f24a/traitsui/__init__.py#L89
https://github.com/enthought/traitsui/blob/b7b6037810fdc9aa6d52a016ec46444e0027f24a/etstool.py#L269-L274

I don't normally run tests via etstool, I run the test suite via python command like you do there. So I run into this error all the time. It stops me from using the `-f` flag on `discover` to stop at the first failure that is meaningful for debugging.
Users installing traitsui from the distribution (e.g. from pip or edm) would also not know about such a set up in order to run test suite with the appropriate tests skipped. So they would get the same confusion when they try to verify their installation.

With that I don't think the current set up is a right one.
