### ISSUE TITLE
Test failure for RangeEditor demo on Wx

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1285]
The following test is failing on wx and OSX:
```
----------------------------------------------------------------------
FAIL: test_run_demo (__main__.TestRangeEditorDemo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/testing/tester/ui_tester.py", line 80, in create_ui
    yield ui
  File "traitsui/examples/demo/Standard_Editors/tests/test_RangeEditor_demo.py", line 78, in test_run_demo
    self.assertEqual(displayed_small, '7')
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '10' != '7'
- 10
+ 7
```

**Comment by aaronayres35** [comment]
Very strange, where did you find this failure?  It doesn't seem to be occurring on the CI build for the PR that introduced the test for the range editor demo: https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/35388893/job/bt71u8o08mqhv2t8

Also, when I run the test locally on master, I am getting:
```
======================================================================
FAIL: test_run_demo (test_RangeEditor_demo.TestRangeEditorDemo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aayres/Desktop/traitsui/traitsui/examples/demo/Standard_Editors/tests/test_RangeEditor_demo.py", line 148, in test_run_demo
    self.assertEqual(displayed_float, '72.0')
  File "/Users/aayres/.edm/envs/wx-env/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/aayres/Desktop/traitsui/traitsui/testing/tester/ui_tester.py", line 92, in create_ui
    process_cascade_events()
  File "/Users/aayres/Desktop/traitsui/traitsui/testing/_gui.py", line 40, in process_cascade_events
    GUI.process_events()
  File "/Users/aayres/Desktop/pyface/pyface/ui/wx/gui.py", line 79, in process_events
    wx.GetApp().Yield(True)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/wincmn.cpp(475) in ~wxWindowBase(): any pushed event handlers must have been removed

----------------------------------------------------------------------
Ran 1 test in 1.321s

FAILED (failures=1)
```
which I don't recall seeing before.

**Comment by kitchoi** [comment]
I am sorry I did not post the command I used. I simply run the test from the test file:
```
$ python traitsui/examples/demo/Standard_Editors/tests/test_RangeEditor_demo.py
```

CI has not been running the integration tests for wx because the first command has failed:
https://github.com/enthought/traitsui/blob/3c11dc6ae6411387096daf981e45ad9360210f8a/etstool.py#L294
The integration tests are run in the second command.

**Comment by aaronayres35** [comment]
> I am sorry I did not post the command I used. I simply run the test from the test file:
> 
> ```
> $ python traitsui/examples/demo/Standard_Editors/tests/test_RangeEditor_demo.py
> ```

When I run this I get the traceback from my comment above, not the one from your comment.  I will investigate more today

**Comment by kitchoi** [comment]
I think I also only showed half of the stderr, cutting out the wxAssertionError that looks to be an overall issue for wx support. This was probably misleading. Here the full output:
```
======================================================================
FAIL: test_run_demo (__main__.TestRangeEditorDemo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/testing/tester/ui_tester.py", line 83, in create_ui
    yield ui
  File "Work/ETS/traitsui/examples/demo/Standard_Editors/tests/test_RangeEditor_demo.py", line 77, in test_run_demo
    self.assertEqual(displayed_small, '7')
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: '10' != '7'
- 10
+ 7


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Work/ETS/traitsui/examples/demo/Standard_Editors/tests/test_RangeEditor_demo.py", line 148, in test_run_demo
    self.assertEqual(displayed_float, '72.0')
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/testing/tester/ui_tester.py", line 95, in create_ui
    process_cascade_events()
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/testing/_gui.py", line 40, in process_cascade_events
    GUI.process_events()
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/gui.py", line 79, in process_events
    wx.GetApp().Yield(True)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/wincmn.cpp(475) in ~wxWindowBase(): any pushed event handlers must have been removed

----------------------------------------------------------------------
Ran 1 test in 0.765s

FAILED (failures=1)
```

Note that I could not reproduce the error on Linux.

**Comment by aaronayres35** [comment]
I'm not seeing this locally when I run the test, and to double check I call `print(displayed_small)` on line 77 right before the assertion that fails and it prints '7' not '10' as it should.

**Comment by kitchoi** [comment]
Thank you very much for looking into this!

**Comment by kitchoi** [comment]
I can reproduce this error on Windows too.

I tried to investigate further and this is my current understanding of the issue:

Key observation of the current code:
When the text editor loses focus, the text editor for wx will update the trait with whatever value is in the textbox at that time.
We have multiple editors editing the same trait, this can cause the focus to jump around when one editor causes the trait to change, causing another editor to update itself.

After adding lots of print functions, I saw this chain of events:
- We modify the textbox value from “1” to “10”
- The trait is changed, the “custom” editor (which is basically a radio enum editor) is updated. This causes the textbox to lose focus.
- We perform a key click on the textbox with the “Enter”, this causes the textbox to gain focus again.
- Then we change the trait on the object to 7. This causes all the editors to try to update their views. This is the part that might be a bug, the text editor, still having the focus, does not update its view to “7”.
- As the custom (the radio enum) editor updates its view, it steals the focus from the textbox. Because the text box loses its focus, it then tries to update the trait. But because the text box value is still “10”, it sets the trait to 10!

If I change 

```
            demo.small_int_range = 7
displayed_small = readonly_small.inspect(DisplayedText())
            self.assertEqual(displayed_small, '7')
```

to this very odd looking code:
```
            demo.small_int_range = 7
            self.assertEqual(demo.small_int_range, 10)
```
then the test passes.

Potential bugs revealed by this:
- Observed: The text editor, while still having the focus, does not update its view when the underlying trait is updated. Expected: The text box should update its view to match the current trait value.
- Observed: The radio enum editor steals focus when it updates in response to the underlying trait change. Expected: the editor should not steal focus it did not have.

Conclusion:
- I can't see anything wrong with what UITester is doing.
- These would be worth opening separate issues (referencing this one) for the two observed bugs above.
