### ISSUE TITLE
Wx test failure on Windows due to locale changes

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1410]
Currently this is the only test that fails on Windows + wxPython 4.1.0 build (There are plenty of failures for wxPython 4.1.0 + OSX or wxPython 4.1.0 + Linux):

```
======================================================================
ERROR: traitsui.tests.ui_editors.test_data_frame_editor (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: traitsui.tests.ui_editors.test_data_frame_editor
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\unittest\loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\unittest\loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\ui_editors\test_data_frame_editor.py", line 19, in <module>
    from pandas import DataFrame
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\pandas\__init__.py", line 30, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\pandas\_libs\__init__.py", line 3, in <module>
    from .tslibs import (
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\pandas\_libs\tslibs\__init__.py", line 3, in <module>
    from .conversion import localize_pydatetime, normalize_date
  File "pandas\_libs\tslibs\c_timestamp.pxd", line 7, in init pandas._libs.tslibs.conversion
  File "pandas\_libs\tslibs\c_timestamp.pyx", line 1, in init pandas._libs.tslibs.c_timestamp
  File "pandas\_libs\tslibs\tzconversion.pyx", line 1, in init pandas._libs.tslibs.tzconversion
  File "pandas\_libs\tslibs\timedeltas.pyx", line 1, in init pandas._libs.tslibs.timedeltas
  File "pandas\_libs\tslibs\offsets.pyx", line 1, in init pandas._libs.tslibs.offsets
  File "pandas\_libs\tslibs\ccalendar.pyx", line 13, in init pandas._libs.tslibs.ccalendar
  File "pandas\_libs\tslibs\strptime.pyx", line 615, in init pandas._libs.tslibs.strptime
  File "pandas\_libs\tslibs\strptime.pyx", line 529, in pandas._libs.tslibs.strptime.TimeRE.__init__
  File "pandas\_libs\tslibs\strptime.pyx", line 404, in pandas._libs.tslibs.strptime.LocaleTime.__init__
  File "pandas\_libs\tslibs\strptime.pyx", line 362, in pandas._libs.tslibs.strptime._getlang
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: en-US

```
This discussion online might be useful: https://discuss.wxpython.org/t/what-is-wxpython-doing-to-the-locale-to-makes-pandas-crash/34606/27

See log: 
[log (15).txt](https://github.com/enthought/traitsui/files/5604327/log.15.txt)

**Comment by kitchoi** [comment]
Upon downgrading to wxPython 4.0 as suggested by the discussion thread, the test did pass. However two other tests in the test suite failed on Windows + wxPython 4.0:
```
2020-11-25T21:52:53.8350204Z test_data_frame_editor (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:53.8940357Z test_data_frame_editor_alternate_adapter (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:53.9472749Z test_data_frame_editor_columns (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.0002528Z test_data_frame_editor_font_mapping (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.0568101Z test_data_frame_editor_format_mapping (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.1111935Z test_data_frame_editor_multi_select (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.1669611Z test_data_frame_editor_numerical_index (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.2316812Z test_data_frame_editor_text_data (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.2875565Z test_data_frame_editor_with_refresh (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.6292414Z test_data_frame_editor_with_update_refresh (traitsui.tests.ui_editors.test_data_frame_editor.TestDataFrameEditor) ... ok
2020-11-25T21:52:54.6293896Z 
2020-11-25T21:52:54.6294675Z ======================================================================
2020-11-25T21:52:54.6295860Z ERROR: test_animated_gif_editor (traitsui.tests.editors.test_animatedGIF_editor.TestAnimatedGIFEditor)
2020-11-25T21:52:54.6297135Z ----------------------------------------------------------------------
2020-11-25T21:52:54.6297855Z Traceback (most recent call last):
2020-11-25T21:52:54.6299106Z   File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\site-packages\traitsui\tests\editors\test_animatedGIF_editor.py", line 44, in test_animated_gif_editor
2020-11-25T21:52:54.6300487Z     from traitsui.wx.animated_gif_editor import AnimatedGIFEditor
2020-11-25T21:52:54.6301770Z   File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\site-packages\traitsui\wx\animated_gif_editor.py", line 22, in <module>
2020-11-25T21:52:54.6302931Z     from wx.adv import Animation, GenericAnimationCtrl
2020-11-25T21:52:54.6304265Z ImportError: cannot import name 'GenericAnimationCtrl' from 'wx.adv' (C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\site-packages\wx\adv.py)
2020-11-25T21:52:54.6305192Z 
2020-11-25T21:52:54.6305677Z ======================================================================
2020-11-25T21:52:54.6306881Z FAIL: test_simple_editor_popup_editor (traitsui.tests.editors.test_image_enum_editor.TestSimpleImageEnumEditor)
2020-11-25T21:52:54.6308244Z ----------------------------------------------------------------------
2020-11-25T21:52:54.6308961Z Traceback (most recent call last):
2020-11-25T21:52:54.6310173Z   File "C:\hostedtoolcache\windows\Python\3.8.6\x64\lib\site-packages\traitsui\tests\editors\test_image_enum_editor.py", line 345, in test_simple_editor_popup_editor
2020-11-25T21:52:54.6311554Z     self.assertEqual(list(editor.control.GetChildren()), [])
2020-11-25T21:52:54.6312800Z AssertionError: Lists differ: [<traitsui.wx.image_enum_editor.ImageEnumDialog object at 0x0000021867CD0A60>] != []
2020-11-25T21:52:54.6313625Z 
2020-11-25T21:52:54.6314213Z First list contains 1 additional elements.
2020-11-25T21:52:54.6314888Z First extra element 0:
2020-11-25T21:52:54.6315738Z <traitsui.wx.image_enum_editor.ImageEnumDialog object at 0x0000021867CD0A60>
2020-11-25T21:52:54.6316434Z 
2020-11-25T21:52:54.6317231Z - [<traitsui.wx.image_enum_editor.ImageEnumDialog object at 0x0000021867CD0A60>]
2020-11-25T21:52:54.6317998Z + []
2020-11-25T21:52:54.6318324Z 
2020-11-25T21:52:54.6318931Z ----------------------------------------------------------------------
2020-11-25T21:52:54.6319609Z Ran 478 tests in 9.440s
```
(see log
[log.txt](https://github.com/enthought/traitsui/files/5601720/log-9.txt)
 for a build on GitHub Actions. There isn't an associated PR because I was experimenting setting up CI with GitHub Actions and came across this.)

**Comment by kitchoi** [comment]
wxPython 4.1.1 was released yesterday and the said test no longer fails. 

The test suite from `python -m unittest discover traitsui` passes on Windows. See log: 
[log (16).txt](https://github.com/enthought/traitsui/files/5604349/log.16.txt)

Appveyor build is still sad but that's because it finally ran the integration tests we weren't running in the past, and revealed errors we weren't seeing before.

Closing.
