### ISSUE TITLE
Trying to pip install with "examples" optional deps fails 

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1458]
Running `pip install traitsui[examples]` fails with 
```
$ pip install traitsui[examples]
Collecting traitsui[examples]
  Using cached traitsui-7.1.1.tar.gz (5.8 MB)
Processing /Users/aayres/Library/Caches/pip/wheels/25/73/54/c034c1b79c3bcac3102f82236ee7fe05e341cd9839ae94c07c/traits-6.1.1-cp36-cp36m-macosx_10_9_x86_64.whl
Processing /Users/aayres/Library/Caches/pip/wheels/8a/cb/ce/962f0e0badb2541174d54446cd2c42be4566752b1cd9f9a335/pyface-7.2.0-py3-none-any.whl
Collecting apptools
  Using cached apptools-5.0.0.tar.gz (182 kB)
Collecting chaco
  Using cached chaco-4.8.0.tar.gz (887 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/aayres/.edm/envs/test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j9/ps8s26f91_1_lgf7mtd4smyr0000gn/T/pip-install-745yd40j/chaco/setup.py'"'"'; __file__='"'"'/private/var/folders/j9/ps8s26f91_1_lgf7mtd4smyr0000gn/T/pip-install-745yd40j/chaco/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/j9/ps8s26f91_1_lgf7mtd4smyr0000gn/T/pip-install-745yd40j/chaco/pip-egg-info
         cwd: /private/var/folders/j9/ps8s26f91_1_lgf7mtd4smyr0000gn/T/pip-install-745yd40j/chaco/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j9/ps8s26f91_1_lgf7mtd4smyr0000gn/T/pip-install-745yd40j/chaco/setup.py", line 7, in <module>
        from numpy import get_include
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

numpy is needed in the environment already in order to install chaco (more specifically to install kiva)

**Comment by kitchoi** [comment]
I'd advocate solving #1139 so that the examples do not require chaco.
(Note that numpy is a build dependency of chaco... but it is not trivial to declare it (see https://github.com/enthought/chaco/pull/467)

**Comment by rahulporuri** [comment]
An error is still raised but the error mode has changed. With the latest releases of enable and chaco, build dependencies are declared using the pyproject.toml file - but swig still needs to be installed manually by the user as it isn't possible via pip.
