### ISSUE TITLE
InstanceEditor with droppable=True crashes on Qt

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#1478]
Setting `droppable=True` on an InstanceEditor when running under Qt crashes with the following error:
```
Traceback (most recent call last):
  File "/Users/cwebster/src/experiments/internal/cwebster/instance_editor/instance_choice_editor.py", line 122, in <module>
    analysis_view.configure_traits(kind='live')
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/handler.py", line 477, in configure_traits
    **args
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traits/has_traits.py", line 2015, in configure_traits
    args,
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 233, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 84, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 126, in __init__
    args=self.args,
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 163, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_base.py", line 286, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 615, in __init__
    layout = self._add_groups(content, inner)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 696, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 617, in __init__
    layout = self._add_items(content, inner)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 891, in _add_items
    editor.prepare(inner)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/editor.py", line 236, in prepare
    self.init(parent)
  File "/Users/cwebster/.edm/envs/edm/lib/python3.6/site-packages/traitsui/qt4/instance_editor.py", line 127, in init
    self.control.installEventFilter(drop_event_filter)
AttributeError: 'NoneType' object has no attribute 'installEventFilter'
```

The proximate cause seems to be that this code:
https://github.com/enthought/traitsui/blob/fb8ea4a4e7df575a707e64cae8eb882a68ef995c/traitsui/qt4/instance_editor.py#L134-L137
occurs before `self.control` is set, so the fix may be as simple as moving the code further down the method.  It is also possible that the code should read `self._choice`  instead of `self.control`.

**Comment by aaronayres35** [comment]
In order for this to occur, `control` needs to have not been set.  It will however be set by this line https://github.com/enthought/traitsui/blob/7e1d9ed6e91e2fe4cc356f4966653a2e889909a4/traitsui/qt4/instance_editor.py#L87-L88

As long as `editable` is `True`.  ~My understanding is that `droppable` would not make sense being True if editable is false?~ I guess the selected object may not editable (just selectable), but we can edit the list of selectable objects by dropping. 

Of the two solutions proposed (moving code down, or using `_choice`), I think both will work, but I prefer the first (as it better preserves the original code).
