### ISSUE TITLE
ObjectColumn sorting with None attributes

### ISSUE THREAD

**Issue by sparsonslab** [enthought/traitsui#1522]
If an object attribute shown in an `ObjectColumn` is `None`, an app-crashing error gets thrown when the user try's to sort (presses the column header). 

e.g.
```
(bacterial_database)bash-3.2$ bi-viewer
.....
2021-02-16 13:38:07 ERROR  [traitsui.qt4.table_model:456] '<' not supported between instances of 'NoneType' and 'NoneType'
Traceback (most recent call last):
 File "/Users/jkic_ji/.edm/envs/bacterial_database/lib/python3.6/site-packages/traitsui/qt4/table_model.py", line 454, in lessThan
  return column.key(left) < column.key(right)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
Traceback (most recent call last):
 File "/Users/jkic_ji/.edm/envs/bacterial_database/lib/python3.6/site-packages/traitsui/qt4/table_model.py", line 454, in lessThan
.....
Abort trap: 6
(bacterial_database)bash-3.2$
```
This is because `ObjectColumn.key(object)` wraps around `ObjectColumn.get_raw_value(object)` which has a general except-catch which returns `None`. However for sorting we need to return `False`.

This could work as a fix:
```
    def key(self, object):
        """ Returns the value to use for sorting.
        """
        raw_value = self.get_raw_value(object)
        return raw_value is not None and raw_value
```

**Comment by sparsonslab** [comment]
Note: the actual trait corresponding to the column doesn't won't normally be None (unless the trait's default is set to that). However ....

If 
`ObjectColumn.name = 'name1.name2.name3'`
and for one particular object,
`name1.name2 = None`
we get an exception if we try to access `name3`. So therefore,
`ObjectColumn.get_raw_value(object)` -> `return None`
And so 'None' will be displayed in the column and also returned by `ObjectColumn.key(object)` - but we can not sort a None.

**Comment by corranwebster** [comment]
I would suggest subclassing `ObjectColumn` to behave as you expect as an immediate work-around - it is intended to be subclassed, in particular the `key` method is a particularly appropriate target for this.

I don't think that there is a global fix for this sort of issue as this is legacy from Python 2 where everything is comparable.  However the sorting code in the TableEditor should have guards around it to catch exceptions from incomparable values so that at a minimum it does not crash.

**Comment by sparsonslab** [comment]
Yes, we did something like that. Thanks Corran.
