### ISSUE TITLE
Help Button issue

### ISSUE THREAD

**Issue by glinsky007** [enthought/traitsui#1538]
When a HelpButton is pushed it does not appear and I get the follow Traceback:

```
Traceback (most recent call last):
  File "/Users/meglinsky/opt/anaconda3/lib/python3.8/site-packages/traitsui/base_panel.py", line 91, in _on_help
    self.ui.handler.show_help(self.ui.info)
  File "/Users/meglinsky/opt/anaconda3/lib/python3.8/site-packages/traitsui/handler.py", line 186, in show_help
    on_help_call()(info, control)
  File "/Users/meglinsky/opt/anaconda3/lib/python3.8/site-packages/traitsui/help.py", line 30, in default_show_help
    toolkit().show_help(info.ui, control)
  File "/Users/meglinsky/opt/anaconda3/lib/python3.8/site-packages/traitsui/qt4/toolkit.py", line 321, in show_help
    ui_panel.show_help(ui, control)
  File "/Users/meglinsky/opt/anaconda3/lib/python3.8/site-packages/traitsui/qt4/ui_panel.py", line 363, in show_help
    html.escape(item.get_label(ui)),
UnboundLocalError: local variable 'html' referenced before assignment
```

**Comment by rahulporuri** [comment]
Thanks for the report @glinsky007. Can you tell us what version of traitsui you are using?

**Comment by glinsky007** [comment]
Using Python 3.8.5, TraitsUI 7.1.1.  Works with Python 2.7.13, and 5.1.0-2.  I am pretty sure that this is close to the last version of TraitsUI that does not have this error  Attached is some minimal code that reproduces the error.
[traits_error_demo.py.zip](https://github.com/enthought/traitsui/files/6141298/traits_error_demo.py.zip)

**Comment by glinsky007** [comment]
Added comments to issue.
