### ISSUE TITLE
ETS Demo application crashes with latest traitsui

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#1620]
Steps to reproduce
---------------------

- Run `edm run -e bootstrap -- python -m etstoool install --toolkit pyqt5`
- Install etsdemo from source i.e. `edn run -e traitsui-test-3.6-pyqt5 -- python -m pip install -e .`
- Create and run etsdemo from a temporary directory i.e. `mkdir temp`, `cd temp`, `etsdemo`
- Select one of the example e.g. "Standard Editors > Button Editor". Then select another example e.g. "Standard Editors > Boolean Editor".
- The ETS Demo app should now crash - with the following traceback on the commandline.

Note that this is a release blocker for the 7.2.0 release (#1569).

```
(traitsui-test-3.6-pyqt5) ...\temp>etsdemo
Traceback (most recent call last):
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\tree_editor.py", line 933, in _on_tree_sel_changed
    self._clear_editor()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\qt4\tree_editor.py", line 775, in _clear_editor
    editor._node_ui.dispose()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\ui.py", line 256, in dispose
    self.finish()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\ui.py", line 278, in finish
    self.reset(destroy=False)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\ui.py", line 315, in reset
    editor.dispose()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\editors\shell_editor.py", line 136, in dispose
    self.update_object, "command_executed", remove=True, dispatch="ui"
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\has_traits.py", line 2330, in observe
    dispatcher=_ObserverDispatchers[dispatch],
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\observe.py", line 59, in observe
    remove=remove,
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 54, in add_or_remove_notifiers
    callable_()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 94, in __call__
    step()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 118, in _add_or_remove_extra_graphs
    remove=self.remove,
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 54, in add_or_remove_notifiers
    callable_()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 94, in __call__
    step()
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\_observe.py", line 150, in _add_or_remove_maintainers
    change_notifier.remove_from(observable)
  File "C:\Users\rporuri\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traits\observation\_observer_change_notifier.py", line 123, in remove_from
    raise NotifierNotFound("Notifier not found.")
traits.observation._exceptions.NotifierNotFound: Notifier not found.
```

**Comment by rahulporuri** [comment]
see related #1612
