### ISSUE TITLE
Tree editor extended selection mode bug

### ISSUE THREAD

**Issue by pyhannes** [enthought/traitsui#1839]
This bug occurs when using a TreeEditor with selection_mode="extended", when multiple items are selected holding the CTRL key.
This only occurs if first a group node and then a child node is selected.

Following code shows the issue with traitsui (7.2.1) on Windows, when first **Business** is selected and then **Jason** while holding CTRL.

It's just the TreeEditor_demo.py example of traitsui with extended selection enabled.

```
from traits.api import HasTraits, Str, Regex, List, Instance

from traitsui.api import Item, View, TreeEditor, TreeNode


class Employee(HasTraits):
    """ Defines a company employee. """

    name = Str('<unknown>')
    title = Str()
    phone = Regex(regex=r'\d\d\d-\d\d\d\d')

    def default_title(self):
        self.title = 'Senior Engineer'


class Department(HasTraits):
    """ Defines a department with employees. """

    name = Str('<unknown>')
    employees = List(Employee)


class Company(HasTraits):
    """ Defines a company with departments and employees. """

    name = Str('<unknown>')
    departments = List(Department)
    employees = List(Employee)


# Create an empty view for objects that have no data to display:
no_view = View()

# Define the TreeEditor used to display the hierarchy:
tree_editor = TreeEditor(
    nodes=[
        # The first node specified is the top level one
        TreeNode(
            node_for=[Company],
            auto_open=True,
            # child nodes are
            children='',
            label='name',  # label with Company name
            view=View(['name'])
        ),
        TreeNode(
            node_for=[Company],
            auto_open=True,
            children='departments',
            label='=Departments',  # constant label
            view=no_view,
            add=[Department],
         ),
        TreeNode(
            node_for=[Company],
            auto_open=True,
            children='employees',
            label='=Employees',   # constant label
            view=no_view,
            add=[Employee]
        ),
        TreeNode(
            node_for=[Department],
            auto_open=True,
            children='employees',
            label='name',   # label with Department name
            view=View(['name']),
            add=[Employee]
        ),
        TreeNode(
            node_for=[Employee],
            auto_open=True,
            label='name',   # label with Employee name
            view=View(['name', 'title', 'phone'])
        )
    ],
    selection_mode="extended",
)


class Partner(HasTraits):
    """ Defines a business partner."""

    name = Str('<unknown>')
    company = Instance(Company)

    traits_view = View(
        Item(name='company', editor=tree_editor, show_label=False),
        title='Company Structure',
        buttons=['OK'],
        resizable=True,
        style='custom',
        width=.3,
        height=500
    )


# Create an example data structure:
jason = Employee(name='Jason', title='Senior Engineer', phone='536-1057')
mike = Employee(name='Mike', title='Senior Engineer', phone='536-1057')
dave = Employee(name='Dave', title='Senior Developer', phone='536-1057')
martin = Employee(name='Martin', title='Senior Engineer', phone='536-1057')
duncan = Employee(name='Duncan', title='Consultant', phone='526-1057')

# Create the demo:
demo = Partner(
    name='Enthought, Inc.',
    company=Company(
        name='Enthought',
        employees=[dave, martin, duncan, jason, mike],
        departments=[
            Department(
                name='Business',
                employees=[jason, mike]
            ),
            Department(
                name='Scientific',
                employees=[dave, martin, duncan]
            )
        ]
    )
)

# Run the demo (if invoked from the command line):
if __name__ == '__main__':
    demo.configure_traits()

```

Error message:
```
Traceback (most recent call last):
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\tree_editor.py", line 943, in _on_tree_sel_changed
    ui = object.edit_traits(
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traits\has_traits.py", line 1822, in edit_traits
    return view.ui(
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\view.py", line 454, in ui
    ui.ui(parent, kind)
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\ui.py", line 238, in ui
    self.rebuild(self, parent)
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\toolkit.py", line 157, in ui_subpanel
    ui_panel.ui_subpanel(ui, parent)
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\ui_panel.py", line 73, in ui_subpanel
    _ui_panel_for(ui, parent, True)
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\ui_panel.py", line 79, in _ui_panel_for
    ui.control = control = _Panel(ui, parent, is_subpanel).control
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\ui_panel.py", line 145, in __init__
    self.control = panel(ui)
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\ui_panel.py", line 274, in panel
    panel = _GroupPanel(content[0], ui).control
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\ui_panel.py", line 632, in __init__
    layout = self._add_items(content, inner)
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\qt4\ui_panel.py", line 865, in _add_items
    editor = factory_method(
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\editor_factory.py", line 119, in simple_editor
    return self.simple_editor_class(
  File "C:\git\test\.tox\py38-dev\lib\site-packages\traitsui\editor.py", line 528, in __init__
    self.old_value = getattr(self.object, self.name)
AttributeError: 'Department' object has no attribute 'title'
```

**Comment by corranwebster** [comment]
Thanks, I can replicate on Mac OS and PyQt5.  I'll look into this and see if there is a quick fix that we can get in to the next release.

**Comment by corranwebster** [comment]
@pyhannes if you have time, could you check whether #1846 fixes for you?

**Comment by pyhannes** [comment]
Thanks for the quick fix. This works for me. Can you tell when the next release will happen?

**Comment by corranwebster** [comment]
Hopefully today, if I don't have too much else going on.  Otherwise, tomorrow.

**Comment by pyhannes** [comment]
Just saw that due to this fix, the "selected" trait of the tree editor does not contain the full list of selected items anymore, since we break out of the loop after the first item. So i think this has to be re-opened?
