### ISSUE TITLE
Importing traitsui.api imports toolkits

### ISSUE THREAD

**Issue by prabhuramachandran** [enthought/traitsui#1866]
The recent traitsui-7.3.0 release introduces something that was not present in earlier releases.  See here: https://github.com/enthought/mayavi/actions/runs/1972206974
and compare this with https://github.com/enthought/mayavi/actions/runs/1937040765 
The only change is the new release. I also confirmed this by downgrading to 7.2.1 here: https://github.com/enthought/mayavi/pull/1139

It would be nice if importing a specific toolkit could be delayed as much as possible.

**Comment by corranwebster** [comment]
I agree, although I thought all the menu code tends to pull that in (but maybe that's only the Pyface toolkit).

I think the PR at fault is https://github.com/enthought/traitsui/pull/1603

**Comment by corranwebster** [comment]
I've opened #1867 to capture this more precisely.

**Comment by corranwebster** [comment]
New hypothesis: we added `ListStrAdapter` and it imports `Color` from the toolkit traits: https://github.com/enthought/traitsui/blob/758a0f0f8136a4da7cd771a8209d001dcac6874b/traitsui/list_str_adapter.py#L28

**Comment by corranwebster** [comment]
OK, so I dug in to see where toolkit selection happens, and it is pretty much immediately because of `Color` traits.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cwebster/src/clean/traitsui/traitsui/api.py", line 257, in <module>
    from .editors.api import ArrayEditor
  File "/Users/cwebster/src/clean/traitsui/traitsui/editors/__init__.py", line 16, in <module>
    from .api import ArrayEditor
  File "/Users/cwebster/src/clean/traitsui/traitsui/editors/api.py", line 96, in <module>
    from .code_editor import CodeEditor
  File "/Users/cwebster/src/clean/traitsui/traitsui/editors/code_editor.py", line 21, in <module>
    class CodeEditor(EditorFactory):
  File "/Users/cwebster/src/clean/traitsui/traitsui/editors/code_editor.py", line 32, in CodeEditor
    mark_color = Color(0xECE9D8)
  File "/Users/cwebster/.edm/envs/traitsui-test-3.6-pyqt5/lib/python3.6/site-packages/traits/trait_factory.py", line 40, in __call__
    return self.maker_function(*args, **metadata)
  File "/Users/cwebster/src/clean/traitsui/traitsui/toolkit_traits.py", line 43, in ColorTrait
    return toolkit().color_trait(*args, **traits)
  File "/Users/cwebster/src/clean/traitsui/traitsui/toolkit.py", line 107, in toolkit
    raise RuntimeError('finding toolkit!')
RuntimeError: finding toolkit!
```
This import path hasn't changed in the new release.

We _have_ messed with the `Color` trait, however.  Perhaps something is going wrong there.

**Comment by corranwebster** [comment]
Checked: 7.2.1 doesn't select a toolkit when importing `traitsui.api`.  Highly suspicious of `Color` (and possibly `Font` traits).
