### ISSUE TITLE
In enum_editor: "mapper has no attribute mappedInt" if pyside2 < 5.15

### ISSUE THREAD

**Issue by nicolasap-dm** [enthought/traitsui#1877]
Using:
```
  pyface        7.4.1
  pyside2       5.14.2.3
  qt            5.12.6
  traitsui      7.3.1
```
with Python 3.6, on both Windows and Linux, the following:

```python
from traits.api import *
from traitsui.api import *

class TheView(HasTraits):
    toggle = Bool(False)
    view = View(
        Item(
            "toggle", style="custom",
            editor=EnumEditor(values={False: "off", True: "on"}, cols=2),
        ),
    )

TheView().configure_traits()
```

fails with:
```
Traceback (most recent call last):
  File "mwe.py", line 19, in <module>
    TheView().configure_traits()
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traits\has_traits.py", line 2181, in configure_traits
    args,
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\toolkit.py", line 238, in view_application
    context, view, kind, handler, id, scrollable, args
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\view_application.py", line 93, in view_application
    context, view, kind, handler, id, scrollable, args
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\view_application.py", line 133, in __init__
    args=self.args,
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\view.py", line 450, in ui
    ui.ui(parent, kind)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\ui.py", line 234, in ui
    self.rebuild(self, parent)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\toolkit.py", line 168, in ui_live
    ui_live.ui_live(ui, parent)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\ui_live.py", line 52, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\ui_live.py", line 72, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\ui_base.py", line 292, in display_ui
    ui.owner.init(ui, parent, style)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\ui_live.py", line 231, in init
    self.add_contents(panel(ui), bbox)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\ui_panel.py", line 270, in panel
    panel = _GroupPanel(content[0], ui).control
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\ui_panel.py", line 620, in __init__
    layout = self._add_items(content, inner)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\ui_panel.py", line 863, in _add_items
    editor.prepare(inner)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\editor.py", line 250, in prepare
    self.init(parent)
  File "C:\Users\nicola\.edm\envs\the_env\lib\site-packages\traitsui\qt4\enum_editor.py", line 320, in init
    self._mapper.mappedInt.connect(self.update_object)
AttributeError: 'PySide2.QtCore.QSignalMapper' object has no attribute 'mappedInt'
```

On Linux, the snippet works well when upgrading to PySide 5.15.2.

**Comment by corranwebster** [comment]
As I recall, the issue was that `mapped` isn't available on all PySide versions.  This may require digging in to see which versions provide exactly what API.

There are multiple places where this sort of change was made, so this isn't the only place that may need fixing.
