### ISSUE TITLE
issue with Statusbar_demo.py with Python 3.10

### ISSUE THREAD

**Issue by fred4ets** [enthought/traitsui#1886]
Hi,

TryingTraits UI demo Advanced/Statusbar_demo.py, I get the following error message:

Traceback (most recent call last):
  File "/usr/local/src/ETS/traitsui/traitsui/examples/demo/Advanced/Statusbar_demo.py", line 93, in <module>
    popup.configure_traits()
  File "/usr/local/lib/python3.10/dist-packages/traits-6.4.0.dev1784-py3.10-linux-x86_64.egg/traits/has_traits.py", line 2174, in configure_traits
    rc = toolkit().view_application(
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/toolkit.py", line 237, in view_application
    return view_application.view_application(
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/view_application.py", line 92, in view_application
    return ViewApplication(
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/view_application.py", line 127, in __init__
    self.ui = self.view.ui(
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/view.py", line 450, in ui
    ui.ui(parent, kind)
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/ui.py", line 234, in ui
    self.rebuild(self, parent)
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/toolkit.py", line 168, in ui_live
    ui_live.ui_live(ui, parent)
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/ui_live.py", line 52, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/ui_live.py", line 72, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/ui_base.py", line 292, in display_ui
    ui.owner.init(ui, parent, style)
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/ui_live.py", line 231, in init
    self.add_contents(panel(ui), bbox)
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/ui_base.py", line 280, in add_contents
    self._add_statusbar()
  File "/usr/local/lib/python3.10/dist-packages/traitsui-7.4.0.dev7-py3.10.egg/traitsui/qt4/ui_base.py", line 373, in _add_statusbar
    item_control.setMinimumWidth(width)
TypeError: setMinimumWidth(self, int): argument 1 has unexpected type 'float'

I don't get this error with Python 3.9.

Debian x86_64, Python 3.10.4, ETS source from github, python3-pyqt5 5.15.6

**Comment by corranwebster** [comment]
This is caused by a change in Python 3.10 where certain Python C API calls no longer to float->int truncation automatically.
