### ISSUE TITLE
ImageEnumEditor: error when changing value list

### ISSUE THREAD

**Issue by vsinkevich** [enthought/traitsui#1890]
I am used to have an Item in my code like this
`Item('Colormap',editor=EnumEditor(name="object.ColormapList"))`
ColormapList is obviously a list of available Colormaps that can be dynamically updated, works totally fine

Lately I switched to ImageEnumEditor like
`Item('Colormap',editor=ImageEnumEditor(name="object.ColormapList", path=CM.get_image_dir()), style='simple')`
As long as ColormapList does not change, everything works fine, but when attempting to add a new element it raises an error (I hid abs paths): 

```Exception occurred in traits notification handler for event object: TraitChangeEvent(object=<multiphysics.Plot3D.V3D.items.dataitem_grid2d.Grid2DDataItem object at 0x0000018F388D14F0>, name='ColormapList', old=['blue-red', 'black-white'], new=['blue-red', 'black-white', 'turbo'])
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.9.8.0\python-3.9.8.amd64\Lib\site-packages\traits\observation\_trait_event_notifier.py", line 122, in __call__
    self.dispatcher(handler, event)
  File "C:\WinPython-64bit-3.9.8.0\python-3.9.8.amd64\Lib\site-packages\traits\trait_notifiers.py", line 48, in ui_dispatch
    handler(*args, **kw)
  File "C:\WinPython-64bit-3.9.8.0\python-3.9.8.amd64\Lib\site-packages\traitsui\qt4\enum_editor.py", line 147, in _values_changed
    self.rebuild_editor()
  File "C:\WinPython-64bit-3.9.8.0\python-3.9.8.amd64\Lib\site-packages\traitsui\qt4\image_enum_editor.py", line 106, in rebuild_editor
    self.control.model().reset()
AttributeError: 'ImageEnumModel' object has no attribute 'reset' 
```
If is set `style='custom'` the widget works as supposed with the custom style, but as I need a dropdown list, I assume I still need to use simple style

System:
windows 10
Python 3.9.8
traitsui-7.2.1
traits-6.3.2

Thanks

**Comment by vsinkevich** [comment]
I made a simple test by just commenting out `self.control.model().reset()` line. Everything works fine and list of items updates once the trait specified with `name="object.ColormapList"`  has changed. 
I have monkey patched it on my machine, but could anybody look into it and make corresponding change for the future release

**Comment by corranwebster** [comment]
Thanks for the report.  I think this is a duplicate of #844.
