### ISSUE TITLE
Test failures, possibly related to PySide 6.6.1

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#2038]
Some errors I haven’t seen before:
```
======================================================================
FAIL: test_propagate_errors (traitsui.tests.editors.test_instance_editor.TestInstanceEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/traitsui/tests/editors/test_instance_editor.py", line 324, in test_propagate_errors
    self.assertFalse(ok_button.inspect(IsEnabled()))
AssertionError: True is not false

======================================================================
FAIL: test_propagate_errors_switch_selection (traitsui.tests.editors.test_instance_editor.TestInstanceEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/traitsui/tests/editors/test_instance_editor.py", line 348, in test_propagate_errors_switch_selection
    self.assertFalse(ok_button.inspect(IsEnabled()))
AssertionError: True is not false

----------------------------------------------------------------------
```
On MacOS and Windows (but less reliably), Python 3.8-3.11, PySide 6.6.1

**Comment by corranwebster** [comment]
Digging in to the test, it looks like the error flag is getting set and then reset, and the field ends up containing just the last letter typed.

**Comment by corranwebster** [comment]
Seem to be seeing for PySide 6.6.3 as well, after not seeing it on 6.6.2.

**Comment by mdickinson** [comment]
I'm also seeing it on 6.6.3 (specifically, 6.6.3.1).
