### ISSUE TITLE
Tests halt with PySide 6.7.1 on cp311 (Linux)

### ISSUE THREAD

**Issue by itziakos** [enthought/traitsui#2059]
Tests halt on rocky linux on Python 3.11 with PySide6 6.7.1 and one needs to kill the process. From the output the issue is during traitsui.testing.tests.test_exception_handling.TestExceptionHandling.test_error_from_gui_captured_and_raise 

```
[2024-06-12T15:33:11.186Z] b'test_commands_imports (traitsui.testing.tests.test_api.TestApi.test_commands_imports) ... ok'
[2024-06-12T15:33:11.186Z] b'test_exceptions_imports (traitsui.testing.tests.test_api.TestApi.test_exceptions_imports) ... ok'
[2024-06-12T15:33:11.186Z] b'test_locator_imports (traitsui.testing.tests.test_api.TestApi.test_locator_imports) ... ok'
[2024-06-12T15:33:11.187Z] b'test_query_imports (traitsui.testing.tests.test_api.TestApi.test_query_imports) ... ok'
[2024-06-12T15:33:11.187Z] b'test_tester_import (traitsui.testing.tests.test_api.TestApi.test_tester_import) ... ok'
[2024-06-12T15:33:11.187Z] b'test_error_from_gui_captured_and_raise (traitsui.testing.tests.test_exception_handling.TestExceptionHandling.test_error_from_gui_captured_and_raise) ... FAIL'
[2024-06-12T15:33:11.187Z] b''
[2024-06-12T15:33:11.187Z] b'======================================================================'
[2024-06-12T15:33:11.187Z] b'FAIL: test2_test_pyside6 (__main__.Tests.test2_test_pyside6)'
[2024-06-12T15:33:11.187Z] b'----------------------------------------------------------------------'
[2024-06-12T15:33:11.187Z] b'Traceback (most recent call last):'
[2024-06-12T15:33:11.187Z] b'  File "/home/builder/workspace/Buildsystem/test/new/cp311/traitsui-8.0.0/tests/run.py", line 36, in test2_test_pyside6'
[2024-06-12T15:33:11.187Z] b'    self.runpy('
[2024-06-12T15:33:11.187Z] b'  File "/home/builder/workspace/Buildsystem/test/new/cp311/entest_utils.py", line 469, in runpy'
[2024-06-12T15:33:11.187Z] b'    self.run_test_function('
[2024-06-12T15:33:11.187Z] b'  File "/home/builder/workspace/Buildsystem/test/new/cp311/entest_utils.py", line 546, in run_test_function'
[2024-06-12T15:33:11.187Z] b'    self.fail("unexpected test exit code {!r}".format(ret))'
[2024-06-12T15:33:11.187Z] b'AssertionError: unexpected test exit code -15'
[2024-06-12T15:33:11.187Z] b''
[2024-06-12T15:33:11.187Z] b'----------------------------------------------------------------------'
[2024-06-12T15:33:11.187Z] b'Ran 18 tests in 1189.950s'
[2024-06-12T15:33:11.187Z] b'FAILED (failures=1, skipped=11)'
[2024-06-12T15:33:11.187Z] b'==================================================='
[2024-06-12T15:33:11.187Z] b"ENTEST STOP -- TOTAL FAILURES: 1 ('traitsui-8.0.0')"
[2024-06-12T15:33:11.187Z] b'==================================================='
```

**Comment by Edgarruiz856** [comment]
<running edgarplasticos3@hotmail.com Edgarruiz856> Tests halt on rocky linux on Python 3.11 with PySide6 6.7.1 and one needs to kill the process. From the output the issue is during traitsui.testing.tests.test_exception_handling.TestExceptionHandling.test_error_from_gui_captured_and_raise 
> 
> ```
> [2024-06-12T15:33:11.186Z] b'test_commands_imports (traitsui.testing.tests.test_api.TestApi.test_commands_imports) ... ok'
> [2024-06-12T15:33:11.186Z] b'test_exceptions_imports (traitsui.testing.tests.test_api.TestApi.test_exceptions_imports) ... ok'
> [2024-06-12T15:33:11.186Z] b'test_locator_imports (traitsui.testing.tests.test_api.TestApi.test_locator_imports) ... ok'
> [2024-06-12T15:33:11.187Z] b'test_query_imports (traitsui.testing.tests.test_api.TestApi.test_query_imports) ... ok'
> [2024-06-12T15:33:11.187Z] b'test_tester_import (traitsui.testing.tests.test_api.TestApi.test_tester_import) ... ok'
> [2024-06-12T15:33:11.187Z] b'test_error_from_gui_captured_and_raise (traitsui.testing.tests.test_exception_handling.TestExceptionHandling.test_error_from_gui_captured_and_raise) ... FAIL'
> [2024-06-12T15:33:11.187Z] b''
> [2024-06-12T15:33:11.187Z] b'======================================================================'
> [2024-06-12T15:33:11.187Z] b'FAIL: test2_test_pyside6 (__main__.Tests.test2_test_pyside6)'
> [2024-06-12T15:33:11.187Z] b'----------------------------------------------------------------------'
> [2024-06-12T15:33:11.187Z] b'Traceback (most recent call last):'
> [2024-06-12T15:33:11.187Z] b'  File "/home/builder/workspace/Buildsystem/test/new/cp311/traitsui-8.0.0/tests/run.py", line 36, in test2_test_pyside6'
> [2024-06-12T15:33:11.187Z] b'    self.runpy('
> [2024-06-12T15:33:11.187Z] b'  File "/home/builder/workspace/Buildsystem/test/new/cp311/entest_utils.py", line 469, in runpy'
> [2024-06-12T15:33:11.187Z] b'    self.run_test_function('
> [2024-06-12T15:33:11.187Z] b'  File "/home/builder/workspace/Buildsystem/test/new/cp311/entest_utils.py", line 546, in run_test_function'
> [2024-06-12T15:33:11.187Z] b'    self.fail("unexpected test exit code {!r}".format(ret))'
> [2024-06-12T15:33:11.187Z] b'AssertionError: unexpected test exit code -15'
> [2024-06-12T15:33:11.187Z] b''
> [2024-06-12T15:33:11.187Z] b'----------------------------------------------------------------------'
> [2024-06-12T15:33:11.187Z] b'Ran 18 tests in 1189.950s'
> [2024-06-12T15:33:11.187Z] b'FAILED (failures=1, skipped=11)'
> [2024-06-12T15:33:11.187Z] b'==================================================='
> [2024-06-12T15:33:11.187Z] b"ENTEST STOP -- TOTAL FAILURES: 1 ('traitsui-8.0.0')"
> [2024-06-12T15:33:11.187Z] b'==================================================='
> ```
