### ISSUE TITLE
Windows + PySide6 + Python 3.11 failures

### ISSUE THREAD

**Issue by itziakos** [enthought/traitsui#2060]
The following tests fail on Windows under Python 3.11 using PySide6

```
[2024-06-13T15:52:28.337Z] b'======================================================================'
[2024-06-13T15:52:28.337Z] b'ERROR: test_create_ui_reraise_exception (traitsui.testing.tester.tests.test_ui_tester.TestUITesterCreateUI.test_create_ui_reraise_exception)'
[2024-06-13T15:52:28.337Z] b'----------------------------------------------------------------------'
[2024-06-13T15:52:28.337Z] b'Traceback (most recent call last):'
[2024-06-13T15:52:28.338Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\tests\\test_ui_tester.py", line 75, in test_create_ui_reraise_exception'
[2024-06-13T15:52:28.338Z] b'    with tester.create_ui(order, dict(view=view)) as ui:'
[2024-06-13T15:52:28.338Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\contextlib.py", line 144, in __exit__'
[2024-06-13T15:52:28.338Z] b'    next(self.gen)'
[2024-06-13T15:52:28.338Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\ui_tester.py", line 116, in create_ui'
[2024-06-13T15:52:28.338Z] b'    process_cascade_events()'
[2024-06-13T15:52:28.338Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\_gui.py", line 37, in process_cascade_events'
[2024-06-13T15:52:28.338Z] b'    while event_loop.processEvents(QtCore.QEventLoop.ProcessEventsFlag.AllEvents):'
[2024-06-13T15:52:28.338Z] b'          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
[2024-06-13T15:52:28.338Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\pyface\\ui\\qt\\gui.py", line 190, in _dispatch'
[2024-06-13T15:52:28.338Z] b'    self._callable(*self._args, **self._kw)'
[2024-06-13T15:52:28.338Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\tests\\test_ui_tester.py", line 78, in raise_error'
[2024-06-13T15:52:28.338Z] b'    raise ZeroDivisionError()'
[2024-06-13T15:52:28.338Z] b'ZeroDivisionError'
[2024-06-13T15:52:28.338Z] b''
[2024-06-13T15:52:28.338Z] b'======================================================================'
[2024-06-13T15:52:28.338Z] b'ERROR: test_event_processed_with_exception_captured (traitsui.testing.tester.tests.test_ui_wrapper.TestUIWrapperEventProcessed.test_event_processed_with_exception_captured)'
[2024-06-13T15:52:28.338Z] b'----------------------------------------------------------------------'
[2024-06-13T15:52:28.338Z] b'Traceback (most recent call last):'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\tests\\test_ui_wrapper.py", line 459, in test_event_processed_with_exception_captured'
[2024-06-13T15:52:28.339Z] b'    wrapper.perform(1.234)'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\ui_wrapper.py", line 247, in perform'
[2024-06-13T15:52:28.339Z] b'    self._perform_or_inspect(interaction)'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\ui_wrapper.py", line 312, in _perform_or_inspect'
[2024-06-13T15:52:28.339Z] b'    with context():'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\contextlib.py", line 144, in __exit__'
[2024-06-13T15:52:28.339Z] b'    next(self.gen)'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\ui_wrapper.py", line 371, in _event_processed'
[2024-06-13T15:52:28.339Z] b'    _process_cascade_events()'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\_gui.py", line 37, in process_cascade_events'
[2024-06-13T15:52:28.339Z] b'    while event_loop.processEvents(QtCore.QEventLoop.ProcessEventsFlag.AllEvents):'
[2024-06-13T15:52:28.339Z] b'          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\pyface\\ui\\qt\\gui.py", line 190, in _dispatch'
[2024-06-13T15:52:28.339Z] b'    self._callable(*self._args, **self._kw)'
[2024-06-13T15:52:28.339Z] b'  File "C:\\Users\\builder\\.edm\\envs\\build-env\\Lib\\site-packages\\traitsui\\testing\\tester\\tests\\test_ui_wrapper.py", line 445, in raise_error'
[2024-06-13T15:52:28.339Z] b'    raise ZeroDivisionError()'
[2024-06-13T15:52:28.339Z] b'ZeroDivisionError'
[2024-06-13T15:52:28.339Z] b''
[2024-06-13T15:52:28.339Z] b'----------------------------------------------------------------------'
[2024-06-13T15:52:28.339Z] b'Ran 687 tests in 40.524s'
[2024-06-13T15:52:28.339Z] b''
[2024-06-13T15:52:28.339Z] b'FAILED (errors=2, skipped=43)'
```

**Comment by itziakos** [comment]
The same tests fail on linux too.
