### ISSUE TITLE
RuntimeError with selected trait in ListStrEditor 

### ISSUE THREAD

**Issue by jenniportman** [enthought/traitsui#222]
When using a `ListStrEditor` with a `selected` attribute, opening the view a second time and selecting an item leads to a RuntimeError. 

***Code that reproduces the issue*** (close the view the first time it is shown, select an item the second time):
```
from traits.api import Any, HasTraits, List, Str
from traitsui.api import Item, ListStrEditor, View

class SimpleListStrEditor(HasTraits):
    play_list = List(Str,[ "The Merchant of Venice", "Hamlet", "MacBeth"])
    select_item = Any
    view = View(
        Item('play_list', editor=ListStrEditor(selected='select_item'))
    )

demo = SimpleListStrEditor()

if __name__ == '__main__':
    demo.configure_traits()
    demo.configure_traits()
```

***Error***:
```
%run "/Users/jenniportman/Projects/ListStrEditor_break.py"
Exception occurred in traits notification handler for object: <traitsui.qt4.list_str_editor._ListStrEditor object at 0x11ba21530>, trait: selected, old value: None, new value: MacBeth
Traceback (most recent call last):
  File "/Users/jenniportman/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/jenniportman/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/list_str_editor.py", line 279, in _selected_changed
    self._selected_index_changed(selected_index)
  File "/Users/jenniportman/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/list_str_editor.py", line 285, in _selected_index_changed
    smodel = self.list_view.selectionModel()
RuntimeError: Internal C++ object (_ListView) already deleted.
ERROR:traits:Exception occurred in traits notification handler for object: <traitsui.qt4.list_str_editor._ListStrEditor object at 0x11ba21530>, trait: selected, old value: None, new value: MacBeth
Traceback (most recent call last):
  File "/Users/jenniportman/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/jenniportman/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/list_str_editor.py", line 279, in _selected_changed
    self._selected_index_changed(selected_index)
  File "/Users/jenniportman/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/list_str_editor.py", line 285, in _selected_index_changed
    smodel = self.list_view.selectionModel()
RuntimeError: Internal C++ object (_ListView) already deleted.
```

***Fix***: 
Adding 
`super( Editor, self ).dispose()`
to the `dispose` method of the `ListStrEditor` class fixes the error for this particular editor. Not sure if other editors suffer from this issue.

**Comment by corranwebster** [comment]
@jenniportman Could you please put together a PR with the fix.  I'd like to add unit tests to it before merging, but having the basic fix available is a start.
