### ISSUE TITLE
Error in qt4/editor.py _visible_changed when having a group within a split.

### ISSUE THREAD

**Issue by bergtholdt** [enthought/traitsui#227]
The following minimal code example causes an AttributeError in the above mentioned method:

``` python
from traits.api import *
from traitsui.api import *

class A(HasTraits):
    i = Int(1)
    v = Bool(False)
    view = View(
            VSplit(
                HGroup(
                    Item('i'),
                    visible_when='v',
                ),
            ),
        )

a = A()
a.edit_traits()
```

The error message is

```
Exception occurred in traits notification handler for object: <traitsui.qt4.ui_panel.GroupEditor object at 0x000000000C2C0DB0>, trait: visible, old value: True, new value: False
Traceback (most recent call last):
  File "C:\x64\Python27\lib\site-packages\traits-4.6.0.dev-py2.7-win-amd64.egg\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\x64\Python27\lib\site-packages\traitsui-4.5.0.dev-py2.7.egg\traitsui\qt4\editor.py", line 158, in _visible_changed
    if page is None or page.parent() is None or page.parent().parent() is None or page.layout().count() != 1:
AttributeError: 'NoneType' object has no attribute 'count'
ERROR:traits:Exception occurred in traits notification handler for object: <traitsui.qt4.ui_panel.GroupEditor object at 0x000000000C2C0DB0>, trait: visible, old value: True, new value: False
Traceback (most recent call last):
  File "C:\x64\Python27\lib\site-packages\traits-4.6.0.dev-py2.7-win-amd64.egg\traits\trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "C:\x64\Python27\lib\site-packages\traitsui-4.5.0.dev-py2.7.egg\traitsui\qt4\editor.py", line 158, in _visible_changed
    if page is None or page.parent() is None or page.parent().parent() is None or page.layout().count() != 1:
AttributeError: 'NoneType' object has no attribute 'count'
Exception occurred in traits notification handler.
Please check the log file for details.
```

apparently there is no layout returned. so maybe a simple fix could be simply replacing the line 158 with:

``` python
        if page is None or page.parent() is None or page.parent().parent() is None or page.layout() is None or page.layout().count() != 1:
```

It does work for me.

**Comment by corranwebster** [comment]
This appears to have been fixed at some point.  Closing.
