### ISSUE TITLE
wx tests fail on travis-ci 

### ISSUE THREAD

**Issue by itziakos** [enthought/traitsui#231]
```python

======================================================================
ERROR: traitsui.tests.test_actions.test_wx_toolbar_action
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/enthought/traitsui/traitsui/tests/test_actions.py", line 150, in test_wx_toolbar_action
    _test_actions(_wx_trigger_toolbar_action)
  File "/home/travis/build/enthought/traitsui/traitsui/tests/test_actions.py", line 83, in _test_actions
    trigger_action_func(ui)
  File "/home/travis/build/enthought/traitsui/traitsui/tests/test_actions.py", line 148, in _wx_trigger_toolbar_action
    toolbar.ProcessEvent(click_event)
AttributeError: 'NoneType' object has no attribute 'ProcessEvent'

======================================================================
FAIL: traitsui.tests.editors.test_range_editor_spinner.test_wx_spin_control_editing_does_not_update
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/enthought/traitsui/traitsui/tests/editors/test_range_editor_spinner.py", line 113, in test_wx_spin_control_editing_does_not_update
    assert num.number == 4
AssertionError

======================================================================
FAIL: traitsui.tests.editors.test_range_editor_text.test_wx_spin_control_editing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/enthought/traitsui/traitsui/tests/editors/test_range_editor_text.py", line 64, in test_wx_spin_control_editing
    assert num.number >= 3 and num.number <=8
AssertionError

======================================================================
FAIL: traitsui.tests.test_visible_when_layout.test_visible_when_layout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/enthought/traitsui/traitsui/tests/test_visible_when_layout.py", line 87, in test_visible_when_layout
    nose.tools.assert_less(size[1], _TEXT_HEIGHT+150)
AssertionError: 307 not less than 250

----------------------------------------------------------------------
Ran 40 tests in 0.533s

FAILED (SKIP=17, errors=1, failures=3)
```

**Comment by corranwebster** [comment]
Also, Wx tests are now stalling in some situations, probably because they pop up a user-visible dialog with log information about bad sRGB profiles. See http://trac.wxwidgets.org/ticket/15331
