### ISSUE TITLE
ArrayEditor throws errors when displaying a 2D array

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/traitsui#248]
The default `ArrayEditor` throws errors when displaying a 2D array:
```
ERROR:traits:Exception occurred in traits notification handler for object: <traitsui.editors.tuple_editor.TupleStructure object at 0x11c5d1770>, trait: f1, old value: [ 3.4906585   4.1887902   4.88692191  5.58505361  6.28318531], new value: [ 3.4906585   4.1887902   4.88692191  5.58505361  6.28318531]
Traceback (most recent call last):
  File "/Users/jrocher/Projects/ETS_source/traits/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/jrocher/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/editors/tuple_editor.py", line 225, in _field_changed
    if new != value[ index ]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

To reproduce the issue, run:
```
from numpy import linspace, pi
from traits.api import HasTraits, Array
from traitsui.api import View, Item

x = linspace(0, 2*pi, 10)
x = x.reshape((2, 5))

class A(HasTraits):
    x = Array()
    view = View(Item("x", show_label=False),)

dc = A(x=x)
dc.configure_traits()
```

**Comment by corranwebster** [comment]
You need to specify that the array is 2D in the trait, so that the editor knows the expected dimensionality:

```
from numpy import linspace, pi
from traits.api import HasTraits, Array
from traitsui.api import View, Item

x = linspace(0, 2*pi, 10)
x = x.reshape((2, 5))

class A(HasTraits):
    x = Array(shape=(None, None))  # or (2, 5) if you know for sure that's the shape, etc.
    view = View(Item("x", show_label=False),)

dc = A(x=x)
dc.configure_traits()
```

In general I would recommend using the `ArrayViewEditor` instead.  It's generally much better, more flexible and handles bigger arrays more gracefully.
