### ISSUE TITLE
ListEditor menus segfault wxPython on OS X

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#337]
Running the standard ListEditor demo, I get this when modifying the list in place (ie. add item or delete item) via the ListEditor menu.  Suspect that things are not being disconnected correctly.

Traceback:
```
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <__main__.ListEditorDemo object at 0x116bf3cb0>, trait: play_list, old value: ['The Merchant of Venice', 'Hamlet', 'MacBeth'], new value: ['The Merchant of Venice', 'Hamlet']
Traceback (most recent call last):
  File "/Users/cwebster/src/ets/traits/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/cwebster/src/ets/traits/traits/trait_notifiers.py", line 614, in dispatch
    handler( *args )
  File "/Users/cwebster/src/ets/traitsui/traitsui/editor.py", line 379, in _update_editor
    self.update_editor()
  File "/Users/cwebster/src/ets/traitsui/traitsui/wx/list_editor.py", line 186, in update_editor
    list_pane.DestroyChildren()
  File "/Users/cwebster/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/wx/_core.py", line 9191, in DestroyChildren
    return _core_.Window_DestroyChildren(*args, **kwargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/vagrant/pisi-64bit/tmp/wxPython-3.0.2.0-3/work/wxPython-src-3.0.2.0/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Exception occurred in traits notification handler for object: <__main__.ListEditorDemo object at 0x116bf3cb0>, trait: play_list, old value: ['The Merchant of Venice', 'Hamlet', 'MacBeth'], new value: ['The Merchant of Venice', 'Hamlet']
Traceback (most recent call last):
  File "/Users/cwebster/src/ets/traits/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/cwebster/src/ets/traits/traits/trait_notifiers.py", line 614, in dispatch
    handler( *args )
  File "/Users/cwebster/src/ets/traitsui/traitsui/editor.py", line 379, in _update_editor
    self.update_editor()
  File "/Users/cwebster/src/ets/traitsui/traitsui/wx/list_editor.py", line 186, in update_editor
    list_pane.DestroyChildren()
  File "/Users/cwebster/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/wx/_core.py", line 9191, in DestroyChildren
    return _core_.Window_DestroyChildren(*args, **kwargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/vagrant/pisi-64bit/tmp/wxPython-3.0.2.0-3/work/wxPython-src-3.0.2.0/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Exception occurred in traits notification handler for object: <__main__.ListEditorDemo object at 0x116bf3cb0>, trait: play_list, old value: ['The Merchant of Venice', 'Hamlet', 'MacBeth'], new value: ['The Merchant of Venice', 'Hamlet']
Traceback (most recent call last):
  File "/Users/cwebster/src/ets/traits/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/cwebster/src/ets/traits/traits/trait_notifiers.py", line 614, in dispatch
    handler( *args )
  File "/Users/cwebster/src/ets/traitsui/traitsui/editor.py", line 379, in _update_editor
    self.update_editor()
  File "/Users/cwebster/src/ets/traitsui/traitsui/wx/list_editor.py", line 186, in update_editor
    list_pane.DestroyChildren()
  File "/Users/cwebster/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/wx/_core.py", line 9191, in DestroyChildren
    return _core_.Window_DestroyChildren(*args, **kwargs)
PyAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/vagrant/pisi-64bit/tmp/wxPython-3.0.2.0-3/work/wxPython-src-3.0.2.0/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Traceback (most recent call last):
  File "<string>", line 2, in handler
  File "/Users/cwebster/src/ets/traitsui/traitsui/wx/list_editor.py", line 438, in delete_item
    self.update_editor()
  File "/Users/cwebster/src/ets/traitsui/traitsui/wx/list_editor.py", line 186, in update_editor
    list_pane.DestroyChildren()
  File "/Users/cwebster/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/wx/_core.py", line 9191, in DestroyChildren
    return _core_.Window_DestroyChildren(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/vagrant/pisi-64bit/tmp/wxPython-3.0.2.0-3/work/wxPython-src-3.0.2.0/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
Segmentation fault: 11
```

**Comment by braidedlogix** [comment]
In my wxPython Phoenix Python 3.6 ETS sandbox, this demo also segfaulted. The problem arose from some issues in traitsui/wx/menu.py. First it nagged about deprecated wx.EVT_MENU(self.window, handler, id=cur_id), which went away with a change to  self.window.Bind(wx.EVT_MENU, handler, id=cur_id). Once changed, for Python 3, the exec functions immediately before this statement used to define "handler" needed updating. Anyway, it's not segfaulting now and appears to be running properly.
