### ISSUE TITLE
Type error kiwisolver.Expression and unicode

### ISSUE THREAD

**Issue by achabotl** [enthought/traitsui#339]
The following example raises a `TypeError: unsupported operand type(s) for !=: 'kiwisolver.Expression' and 'unicode'`.

I've tried to pare down the example as much as possible but it's not quite minimal. 

Chaco version: 4.6.0
Traits version: 4.6.0
Traitsui version: 5.1.0
Python 2.7.11 on OS X, 64 bits.

## Small example
```python
from chaco.api import Plot
from enable.component_editor import ComponentEditor
from traits.api import Button, HasTraits, Instance
from traitsui.api import Handler, View
from chaco.api import LassoOverlay


class ScatterPlotHandler(Handler):
    def object_edit_overlay_changed(self, info):
        info.object.plot.overlays[-1].edit_traits(parent=info.ui.control)
        return

class ScatterPlot(HasTraits):

    plot = Instance(Plot)

    edit_overlay = Button('Edit Overlay')

    traits_view = View('plot',
                      'edit_overlay',
                       handler = ScatterPlotHandler)

    def _plot_default(self):
        # Create the data and the PlotData object
        plot = Plot()
        plot.overlays.append(LassoOverlay())
        return plot


demo = ScatterPlot()

if __name__ == "__main__":
    demo.configure_traits()
```

## Traceback
```python
libpng warning: iCCP: known incorrect sRGB profile
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <__main__.ScatterPlot object at 0x11f13ea10>, trait: edit_overlay, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
    self.dispatch( handler, *args )
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/trait_notifiers.py", line 614, in dispatch
    handler( *args )
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/ui.py", line 1010, in dispatch
    self.method( self.info )
  File "custom_overlay_dataspace.py", line 10, in object_edit_overlay_changed
    info.object.plot.overlays[-1].edit_traits(parent=info.ui.control)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traits/has_traits.py", line 1871, in edit_traits
    handler, id, scrollable, args )
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 155, in ui_live
    ui_live.ui_live( ui, parent )
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/ui_live.py", line 39, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/ui_live.py", line 59, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/ui_base.py", line 482, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/ui_live.py", line 177, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 255, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 592, in __init__
    layout = self._add_items(content, inner)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 860, in _add_items
    editor.prepare(inner)
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/editor.py", line 158, in prepare
    self.update_editor()
  File "/Users/achabot/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/traitsui/qt4/text_editor.py", line 142, in update_editor
    unequal = bool(user_value != self.value)
TypeError: unsupported operand type(s) for !=: 'kiwisolver.Expression' and 'unicode'
```

**Comment by rkern** [comment]
You'll have to define the `View` that you want to use for the `LassoOverlay`. It does not provide one, and the autogenerated one is not guaranteed to do something sensible for every object type that overrides basic object functionality like `__ne__`.
