### ISSUE TITLE
missing dependency over numpy?

### ISSUE THREAD

**Issue by stefanoborini** [enthought/traitsui#341]
I just noted that if you go with wx backend you end up with the following exception

```
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/image_slice.py", line 32, in <module>
    from numpy \
ImportError: No module named numpy
```

I guess it's a missing dependency?

Version is 5.1.0 on OSX

**Comment by rkern** [comment]
Can you provide more context in the traceback? This is only used by the deprecated theming engine, which we should just delete instead of adding the dependency.

**Comment by stefanoborini** [comment]
Here is the full traceback

```
Traceback (most recent call last):
  File "/Users/sborini/.edm/envs/simphony-metaedit/bin/simphony-metaedit", line 9, in <module>
    load_entry_point('simphony-metaedit', 'gui_scripts', 'simphony-metaedit')()
  File "/Users/sborini/Work/github/simphony/simphony-metaedit/simphony_metaedit/run.py", line 35, in main
    a.configure_traits()
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/handler.py", line 459, in configure_traits
    scrollable, **args )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traits/has_traits.py", line 2172, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/toolkit.py", line 219, in view_application
    id, scrollable, args )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/view_application.py", line 93, in view_application
    scrollable, args ).ui.result
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/view_application.py", line 141, in __init__
    super( ViewApplication, self ).__init__(0)
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/view_application.py", line 158, in OnInit
    args       = self.args )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/toolkit.py", line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 223, in init
    sw = panel( ui, window )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 338, in panel
    content[0], ui )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 647, in __init__
    self.add_notebook_item )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 391, in create_notebook_for_items
    is_dock_window = True )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 661, in __init__
    self.add_items(content, panel, self.sizer)
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 1020, in add_items
    editor.prepare( item_panel )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/editor.py", line 158, in prepare
    self.update_editor()
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/instance_editor.py", line 373, in update_editor
    self.resynch_editor()
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/instance_editor.py", line 435, in resynch_editor
    self.factory.id )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/toolkit.py", line 126, in ui_subpanel
    ui_panel.ui_subpanel( ui, parent )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 97, in ui_subpanel
    ui_panel_for( ui, parent, False )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 110, in ui_panel_for
    ui.control = control = Panel( ui, parent, buttons ).control
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 196, in __init__
    sw = panel( ui, cpanel )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 338, in panel
    content[0], ui )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 659, in __init__
    self.add_groups( content, panel )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 811, in add_groups
    fill_panel_for_group( panel, subgroup, self.ui )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 661, in __init__
    self.add_items(content, panel, self.sizer)
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 974, in add_items
    border=group.show_border )
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/ui_panel.py", line 1163, in create_label
    from image_text import ImageText
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/image_text.py", line 27, in <module>
    from image_slice \
  File "/Users/sborini/.edm/envs/simphony-metaedit/lib/python2.7/site-packages/traitsui/wx/image_slice.py", line 32, in <module>
    from numpy \
ImportError: No module named numpy
```

**Comment by corranwebster** [comment]
Yes, this looks like it is from the theming stuff.  You need numpy to run on Wx at the moment, but as @rkern notes the correct fix is to remove the theming stuff.

**Comment by corranwebster** [comment]
Looking at the traceback, it appears that this is invoked by the `create_label` which creates a custom static text widget with a themed background (an ImageText).  We can probably just replace this with a plain StaticText and fix the immediate problem.

**Comment by corranwebster** [comment]
Having spent some time trying to remove theming (see #342) the current state is:

* tabbed groups require dock window themes
* dock window themes require traitsui themes
* traitsui themes need to slice images to determine how to draw borders, etc.
* image slicing uses numpy

I will look into whether we can avoid custom drawing of tabs, but until that is removed, traitsui for wx will require numpy.

**Comment by rahulporuri** [comment]
I'm going to close this issue as we already document the fact that `numpy` is a required dependency for the use of `traitsui` with the `wx` toolkit - and we don't plan on fixing that anytime soon.

> I will look into whether we can avoid custom drawing of tabs, but until that is removed, traitsui for wx will require numpy.

@corranwebster do you think it is worth creating a separate issue to track your earlier comment? https://github.com/enthought/traitsui/issues/341#issuecomment-278903723
