### ISSUE TITLE
Get NotImplementedError when using configure_traits

### ISSUE THREAD

**Issue by minghigh** [enthought/traitsui#349]
I ran a simple sample code

```python
from traits.api import HasTraits, Str, Int
from traitsui.api import View, Item
from traitsui.menu import OKButton, CancelButton


class SimpleEmployee(HasTraits):
    first_name = Str
    last_name = Str
    department = Str

    employee_number = Str
    salary = Int


view1 = View(Item(name='first_name'),
             Item(name='last_name'),
             Item(name='department'),
             buttons=[OKButton, CancelButton])

sam = SimpleEmployee()
sam.configure_traits(view=view1)
```

But got the following error

```
Traceback (most recent call last):
  File "C:/Users/minghigh/Desktop/workspace/python/untitled/test.py", line 22, in <module>
    sam.configure_traits(view=view1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traits\has_traits.py", line 2171, in configure_traits
    kind, handler, id, scrollable, args )
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitsui\toolkit.py", line 291, in view_application
    raise NotImplementedError
NotImplementedError
```

My environment:

- python 3.6
- numpy 1.11.3
- traitsui 5.1.0
- traits 4.6.0

and i use win10:)

**Comment by corranwebster** [comment]
Which backend are you using, `qt4` or `wx`?  And if `qt4` are you using Pyside or PyQt4.

Note also that 5.1.0 does not support Qt5, so you may need to install Qt4.

**Comment by corranwebster** [comment]
I am assuming that this was a Qt5 issue.  Closing.
