### ISSUE TITLE
TabularEditor: use of refresh triggers AttributeError under TRAITS_DEBUG

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#368]
When using the `TabularEditor` on Qt with a specified `refresh` trait (and probably also wx) under `TRAITS_DEBUG`, we get the following exception (once #366 is fixed):
```
AttributeError: The refresh trait of a Report instance is an 'event', which is write only.
```

Code to reproduce:
```python
from traits.api import HasTraits, Str, Int, List, Event
from traitsui.api import View, Group, Item, TabularEditor
from traitsui.tabular_adapter import TabularAdapter


class Person(HasTraits):
    name = Str
    age = Int


class ReportAdapter(TabularAdapter):
    columns = [('Name', 'name'), ('Age', 'age')]


class Report(HasTraits):
    refresh = Event

    people = List(Person)

    view = View(
        Group(
            Item(
                'people',
                editor=TabularEditor(
                    adapter=ReportAdapter(),
                    refresh='refresh',
                ),
            ),
        ),
    )


Report(
    people=[
        Person(name='Theresa', age=60),
        Person(name='Arlene', age=46),
    ]
).configure_traits()
```

When run without `TRAITS_DEBUG` set, this works normally. When run with `TRAITS_DEBUG=1 python example.py`, I get the following traceback.

```
(geophysics)bash-3.2$ TRAITS_DEBUG=1 python ~/Desktop/example.py 
Traceback (most recent call last):
  File "/Users/mdickinson/Desktop/example.py", line 36, in <module>
    Person(name='Arlene', age=46),
  File "/Users/mdickinson/.edm/envs/geophysics/lib/python2.7/site-packages/traits/has_traits.py", line 2172, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/toolkit.py", line 231, in view_application
    id, scrollable, args)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/view_application.py", line 84, in view_application
    scrollable, args).ui.result
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/view_application.py", line 136, in __init__
    args=self.args)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/view.py", line 455, in ui
    ui.ui(parent, kind)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/ui.py", line 234, in ui
    self.rebuild(self, parent)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/toolkit.py", line 173, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/ui_live.py", line 40, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/ui_live.py", line 62, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/ui_base.py", line 486, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/ui_live.py", line 202, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/ui_panel.py", line 263, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/ui_panel.py", line 603, in __init__
    layout = self._add_items(content, inner)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/ui_panel.py", line 871, in _add_items
    editor.prepare(inner)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/editor.py", line 169, in prepare
    self.init(parent)
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/qt4/tabular_editor.py", line 169, in init
    self.sync_value(factory.refresh, 'refresh', 'from')
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/editor.py", line 549, in sync_value
    raise_to_debug()
  File "/Users/mdickinson/Enthought/Projects/Canopy_Geoscience/traitsui/traitsui/editor.py", line 546, in sync_value
    setattr(self, editor_name, eval(user_value))
  File "<string>", line 1, in <module>
AttributeError: The refresh trait of a Report instance is an 'event', which is write only.
```

**Comment by mdickinson** [comment]
The underlying issue here is that `sync_value` wants to read the value of the Trait it's syncing with, and that triggers an `AttributeError` for `Event` traits.

**Comment by peterzahemszky** [comment]
There's an issue with the tree editor that's very similar to this one
