### ISSUE TITLE
NotImplementedError when use tvtk_doc.main()

### ISSUE THREAD

**Issue by webMing** [enthought/traitsui#377]
>>> from tvtk.tools import tvtk_doc
>>> tvtk_doc.main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/mayavi-4.5.0-py3.5-macosx-10.6-x86_64.egg/tvtk/tools/tvtk_doc.py", line 403, in main
    s.configure_traits()
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traits/has_traits.py", line 2156, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/apple/anaconda/envs/python3.5/lib/python3.5/site-packages/traitsui/toolkit.py", line 291, in view_application
    raise NotImplementedError
NotImplementedError

my envs:
pyqt:5.6.0 py35_2 
qt:5.6.2
tvk: 7.0.0 py35_0
python:3.5
macOS:10.12

anyone encounter this? and how to solve ?  Thanks advance!

**Comment by corranwebster** [comment]
I assume this is with the most recent released TraitsUI 5.1?  If so, the problem is that that version does not support Qt5 (and neither does current Mayavi).  You will need to downgrade to Qt4 in your environment.
