### ISSUE TITLE
Appveyor tests are stuck on current master

### ISSUE THREAD

**Issue by itziakos** [enthought/traitsui#421]
Appveyor builds are stuck on when running on current master 06677a9e10b3bb6c2dc2e54bc137e72b6f39640d. The build is stuck on the python 3.5 tests using pyqt5.

locally on a windows 10 machine the python 3.5 pyqt5 tests run and fail with the following traceback

```python
======================================================================
FAIL: traitsui.tests.test_splitter_prefs_restored.test_splitter_prefs_are_restored
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\...\.edm\envs\traitsui-test-3.5-pyqt5\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\...\.edm\envs\traitsui-test-3.5-pyqt5\lib\site-packages\traitsui-5.2.0.dev356-py3.5.egg\traitsui\tests\_tools.py", line 88, in wrapper
    return item(*args, **kwargs)
  File "C:\Users\...\.edm\envs\traitsui-test-3.5-pyqt5\lib\site-packages\traitsui-5.2.0.dev356-py3.5.egg\traitsui\tests\test_splitter_prefs_restored.py", line 136, in test_splitter_prefs_are_restored
    _get_nattr(ui2.get_prefs()))
AssertionError: b'\x0[54 chars]x00\x00\x00\x00\x02M\x01\xff\xff\xff\xff\x00\x[14 chars]\x01' != b'\x0[54 chars]x00\x89\x00\x00\x02"\x01\xff\xff\xff\xff\x00\x[14 chars]\x01'
```

**Comment by itziakos** [comment]
I am trying to investigate the issue in #420
