### ISSUE TITLE
Bug: Enum with values fails when embedded within another object

### ISSUE THREAD

**Issue by jonathanrocher** [enthought/traitsui#477]
In the following code, I would expect A and A2 to be interchangeable:
```
from traits.api import HasStrictTraits, Instance, Enum, List
from traitsui.api import View, Item

class A(HasStrictTraits):
    value = Enum(values="value_list")
    value_list = List(list("abcde"))

class A2(HasStrictTraits):
    value = Enum(list("abcde"))

class B(HasStrictTraits):
    a = Instance(A, (), {"value": "a"})
    view = View(Item("object.a.value"))

b = B()
print(b.a.value)
b.configure_traits()
```
But when trying to `configure_traits` on B when using A, I get the following traceback (traitsui 5.1.0, PyQt, python2.7, OSX):
```
Traceback (most recent call last):
  File "/Users/jrocher/enum_fail_example.py", line 20, in <module>
    b.configure_traits()
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traits/has_traits.py", line 2172, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 213, in view_application
    id, scrollable, args )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/view_application.py", line 83, in view_application
    scrollable, args ).ui.result
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/view_application.py", line 134, in __init__
    args       = self.args )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 155, in ui_live
    ui_live.ui_live( ui, parent )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/ui_live.py", line 39, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/ui_live.py", line 59, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/ui_base.py", line 482, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/ui_live.py", line 177, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 255, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 592, in __init__
    layout = self._add_items(content, inner)
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/ui_panel.py", line 860, in _add_items
    editor.prepare(inner)
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/editor.py", line 156, in prepare
    self.init( parent )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/enum_editor.py", line 186, in init
    super( SimpleEditor, self ).init( parent )
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/enum_editor.py", line 79, in init
    self.values_changed()
  File "/Users/jrocher/.edm/envs/bootstrap/lib/python2.7/site-packages/traitsui/qt4/enum_editor.py", line 141, in values_changed
    enum_values_changed( self._value(), self.string_value )
  File "<string>", line 1, in <lambda>
AttributeError: 'B' object has no attribute 'value_list'
```

**Comment by corranwebster** [comment]
Duplicate of #189?

**Comment by jonathanrocher** [comment]
Right, thanks, it's is a duplicate. My example is slightly simpler since the issue has nothing to do with `DeletegateTo`, but you made that comment there. Closing.
