### ISSUE TITLE
refresh_name trait does not work with Qt FileEditor

### ISSUE THREAD

**Issue by tmreay** [enthought/traitsui#490]
When using a `FileEditor` with a `'custom'` style, the trait assigned to the `refresh_name` attribute throws an exception when that event is triggered.

See below:
```python
class Foo(HasTraits):
    file = File
    refresh = Button('Refresh')
    def default_traits_view(self):
        return View(
            Item('file',
                 editor=FileEditor(reload_name='refresh'),
                 style='custom',
                 show_label=False),
            Item('refresh',
                 show_label=False)
        )

Foo().configure_traits()
```
Pressing "Refresh" causes this exception:
```
Exception occurred in traits notification handler.
Please check the log file for details.
Exception occurred in traits notification handler for object: <traitsui.qt4.file_editor.CustomEditor object at 0x12db7f1a8>,trait: reload, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/Users/mreay/.edm/envs/cleantrack/lib/python3.6/site-packages/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/Users/mreay/.edm/envs/cleantrack/lib/python3.6/site-packages/traitsui/qt4/file_editor.py", line 245, in _reload_changed
    self._model.refresh()
AttributeError: 'QFileSystemModel' object has no attribute 'refresh'
```

**Comment by corranwebster** [comment]
Indeed looks like a bug, possibly a hold-over from an earlier version of Qt.

According to the Qt docs the `QFileSystemModel` should update itself automatically when the files on disk change, so the refresh trait functionality shouldn't be needed.  But maybe I am not seeing the use-case.  What was the behaviour you were expecting to see?

**Comment by tmreay** [comment]
You're right that the `QFileSystemModel` does update automatically on macOS. I am not seeing this behavior in Windows, however. Hence the need to manually update the file view.
