### ISSUE TITLE
Tree_editor_with_TreeNodeRenderer.py example errors on spark line drawing

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#512]
On Ubuntu 18, running `examples/demo/Extras/Tree_editor_with_TreeNodeRenderer.py` gives a host of errors of the sort:

```
Traceback (most recent call last):
  File "/home/matt/local/code/scratch/traitsui/traitsui/qt4/tree_editor.py", line 1973, in paint
    self.editor, node, column, instance, paint_context
  File "examples/demo/Extras/Tree_editor_with_TreeNodeRenderer.py", line 102, in paint
    painter.drawPolyline(points)
TypeError: arguments did not match any overloaded call:
  drawPolyline(self, Union[QPointF, QPoint], *): argument 1 has unexpected type 'list'
  drawPolyline(self, QPolygonF): argument 1 has unexpected type 'list'
  drawPolyline(self, QPoint, *): argument 1 has unexpected type 'list'
  drawPolyline(self, QPolygon): argument 1 has unexpected type 'list'
```

Changing the call at line 102 to `painter.drawPolyline(*points)` fixes the problem. I'm not sure why this works on other systems.

~~edit: pyqt version: `4.8.7`~~
edit edit:
```python
>>> from PyQt4.QtCore import QT_VERSION_STR
>>> QT_VERSION_STR
'4.8.7'
```

**Comment by corranwebster** [comment]
PyQt 4.8.7 (that's very old) or Qt 4.8.7 (much more recent)?

**Comment by jwiggins** [comment]
I also see this with a freshly installed Python 3.6 environment.

PyQt 4.12.1

**Comment by jwiggins** [comment]
It works for me if I do this to the drawing code:
```
if qt_api.startswith('pyside'):
    painter.drawPolyline(points)
else:
    painter.drawPolyline(*points)
```
This assumes that PySide2 doesn't change the interface yet again...

**Comment by notmatthancock** [comment]
> PyQt 4.8.7 (that's very old) or Qt 4.8.7 (much more recent)?

Qt
