### ISSUE TITLE
Default RangeEditor for a Range Trait fails if 'low' or 'high' is a string holding another Trait name.

### ISSUE THREAD

**Issue by WarrenWeckesser** [enthought/traitsui#6]
The 'low' and 'high' arguments of the Range trait can be given strings that hold the names of other traits.  However, attempting to bring up a UI for a class with such a trait will fail.  It appears that the RangeEditor does not handle this case. (The RangeEditor has its own arguments, 'low_name' and 'high_name', to handle the bounds being defined by other traits.)

For example:

``` python
from traits.api import HasTraits, Range, Float, TraitError

class Foo(HasTraits):
    upper = Float(10.0)
    x = Range(low=0.0, high='upper')

if __name__ == "__main__":
    f = Foo()
    f.x = 5.0
    print "f.x is now", f.x
    try:
        f.x = 50.0
    except TraitError:
        print "TraitError exception, as expected."

    # This will fail.
    f.configure_traits()
```

The output is

```
f.x is now 5.0
TraitError exception, as expected.
Traceback (most recent call last):
  File "range_with_named_high.py", line 18, in <module>
    f.configure_traits()
  File "/Users/warren/ets-master/traits/traits/has_traits.py", line 2544, in configure_traits
    kind, handler, id, scrollable, args )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/toolkit.py", line 219, in view_application
    id, scrollable, args )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/view_application.py", line 80, in view_application
    scrollable, args ).ui.result
  File "/Users/warren/ets-master/traitsui/traitsui/wx/view_application.py", line 123, in __init__
    super( ViewApplication, self ).__init__()
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/wx/_core.py", line 8078, in __init__
    wx.App.__init__(self, redirect, filename, useBestVisual, clearSigInt)
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/wx/_core.py", line 7978, in __init__
    self._BootstrapApp()
  File "/Library/Frameworks/Python.framework/Versions/7.0/lib/python2.7/site-packages/wx/_core.py", line 7552, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "/Users/warren/ets-master/traitsui/traitsui/wx/view_application.py", line 140, in OnInit
    args       = self.args )
  File "/Users/warren/ets-master/traitsui/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/Users/warren/ets-master/traitsui/traitsui/ui.py", line 218, in ui
    self.rebuild( self, parent )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/toolkit.py", line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/ui_live.py", line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/ui_live.py", line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/ui_live.py", line 223, in init
    sw = panel( ui, window )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/ui_panel.py", line 349, in panel
    content[0], ui )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/ui_panel.py", line 523, in fill_panel_for_group
    create_panel )
  File "/Users/warren/ets-master/traitsui/traitsui/wx/ui_panel.py", line 672, in __init__
    self.add_items(content, panel, self.sizer)
  File "/Users/warren/ets-master/traitsui/traitsui/wx/ui_panel.py", line 1026, in add_items
    item_panel ).set(
  File "/Users/warren/ets-master/traitsui/traitsui/editors/range_editor.py", line 271, in simple_editor
    return super(RangeEditor, self).simple_editor(ui, object, name, description, parent)
  File "/Users/warren/ets-master/traitsui/traitsui/editor_factory.py", line 130, in simple_editor
    return self.simple_editor_class( parent,
  File "/Users/warren/ets-master/traitsui/traitsui/editors/range_editor.py", line 216, in _get_simple_editor_class
    if (not is_float) and (abs(high - low) > 1000000000L):
TypeError: unsupported operand type(s) for -: 'float' and 'code'
```

**Comment by 22csnyder** [comment]
I ran into the exact same problem today
