### ISSUE TITLE
Issues in demos

### ISSUE THREAD

**Issue by sandhya-sago** [enthought/traitsui#623]
- [ ] examples/demo/Standard_Editors/CompoundEditor_demo.py
Gives traceback error when alphabets are clicked (from second click onwards).
Traceback (most recent call last):
File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/wx/range_editor.py", line 251, in update_object_on_enter self._convert_to_slider(self.value))
File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/wx/range_editor.py", line 297, in _convert_to_slider
   ivalue = int((float(value - self.low) /
TypeError: unsupported operand type(s) for -: 'str' and 'int'

- [ ] examples/demo/Standard_Editors/DirectoryEditor_demo.py 
Traceback when closing or when OK is clicked and does not close.
 Traceback (most recent call last):
   File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 344, in _on_close_page
     self._on_cancel(event)
   File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 398, in _on_cancel
     self.close(wx.ID_CANCEL)
   File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/wx/ui_live.py", line 333, in close
     ui.finish()
   File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/ui.py", line 283, in finish
     self.reset(destroy=False)
   File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/ui.py", line 325, in reset
     editor.dispose()
   File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/traitsui/wx/file_editor.py", line 125, in dispose
     panel.Bind(wx.EVT_BUTTON, self._button.GetId(), None)
   File "/Users/sgovindaraju/.edm/envs/traitsui_tutorial/lib/python2.7/site-packages/wx/_core.py", line 4224, in Bind
     assert handler is None or callable(handler)
 AssertionError

- [ ] examples/demo/Standard_Editors/FileEditor_demo.py
Similar to DirectoryEditor_demo.py

- [ ] examples/demo/Standard_Editors/FontEditor_demo.py
Font changes but the size does not.

**Comment by corranwebster** [comment]
When trying the compound editor under Python 3.6/PyQt5 I don't see the same error, but when I try to use the combobox in the simple editor, I get dialogs popping up with error messages trying to compare string values to integer ranges.

**Comment by corranwebster** [comment]
It looks like the file and directory editor bugs are because of incorrect calls to `Bind`. The line here https://github.com/enthought/traitsui/blob/master/traitsui/wx/file_editor.py#L125 does not match the signature of `Bind`: https://wxpython.org/Phoenix/docs/html/wx.EvtHandler.html#wx.EvtHandler.Bind

The correct call should be something like:
```
panel.Bind(wx.EVT_BUTTON, None, id=self._button.GetId())
```

I suspect the `DirectoryEditor` is the same.

**Comment by corranwebster** [comment]
Looking at the CompoundEditor issue, this is really a problem with the RangeEditor not handling the case of sitting on top of a model holding an invalid (ie. non-numeric) value.  The fix is to have more robust exception handling in `update_object_on_enter` (and possibly other update methods as well).

**Comment by corranwebster** [comment]
The font editor not resizing is deliberate, if sub-optimal.  It does in fact resize if the point size is 10 or less due to this line: https://github.com/enthought/traitsui/blob/master/traitsui/wx/font_editor.py#L384

Experimenting with this, large point sizes result in poor display because the size of the widget doesn't change, leading to obscured text.  Fixing this may be hard, given that sometimes we can't increase the size of the widget.

**Comment by corranwebster** [comment]
The `03:59:54 PM: Warning: iCCP: known incorrect sRGB profile` error in the TreeEditor demo means there is a corrupted icon file somewhere.  Wherever it is it needs to be opened in an image editor and re-saved correctly.

**Comment by corranwebster** [comment]
The line:
```
File "/Users/sgovindaraju/.edm/envs/tutorials_wx/lib/python2.7/site-packages/traitsui/ui.py", line 325, in reset
editor.dispose()
File "/Users/sgovindaraju/.edm/envs/tutorials_wx/lib/python2.7/site-packages/traitsui/wx/file_editor.py", line 125, in dispose
panel.Bind(wx.EVT_BUTTON, self._button.GetId(), None)
```
is coming from the `Bind` signature being incorrect, it should have `id=self._button.GetId()` I think.

**Comment by shoeb-github** [comment]
> examples/demo/Standard_Editors/TupleEditor_demo.py

I did not see the reported behavior on Python 3.6 with pyqt5 or pyqt.
