### ISSUE TITLE
Skip tests that rely on optional dependencies if those dependencies are not installed

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#660]
There are some tests that rely on optional dependencies: `traitsui.tests.test_extras` depends on `configobj`, and `traitsui.tests.ui_editors.test_data_frame_editor` depends on NumPy. It would be good to skip those tests if the corresponding dependencies aren't present in the environment.

**Comment by mdickinson** [comment]
`pygments` is another of these:
```
======================================================================
ERROR: test_tree_editor_label_listener (traitsui.tests.editors.test_tree_editor.TestTreeView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/Desktop/py37/lib/python3.7/site-packages/traitsui/tests/_tools.py", line 129, in wrapper
    return test_func(*args, **kwargs)
  File "/Users/mdickinson/Desktop/py37/lib/python3.7/site-packages/traitsui/tests/editors/test_tree_editor.py", line 223, in test_tree_editor_label_listener
    trait='name')
  File "/Users/mdickinson/Desktop/py37/lib/python3.7/site-packages/traitsui/tests/editors/test_tree_editor.py", line 147, in _test_tree_editor_releases_listeners
    self.assertEqual(expected_listeners, len(notifiers_list))
TypeError: object of type 'NoneType' has no len()
-------------------- >> begin captured logging << --------------------
traitsui.editor_factory: DEBUG: Can't import SimpleEditor for <class 'traitsui.editors.tree_editor.ToolkitEditorFactory'>: No module named 'pygments'
--------------------- >> end captured logging << ---------------------
```
