### ISSUE TITLE
Don't warn about missing numpy in traitsui.api

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#731]
In an environment that doesn't have NumPy installed, importing `traitsui.api` gives a warning:

```
/Users/mdickinson/.venvs/traits-py38/lib/python3.8/site-packages/traitsui/editors/api.py:15: ImportWarning: ArrayEditor is not available due to missing numpy
```

I don't think this should be a warning, or at least not an import time warning: it's legitimate to have need of a Python environment that has TraitsUI but not NumPy.

One option would be to define `ArrayEditor` as a stub in the absence of NumPy, and have that stub warn or raise on first use.

**Comment by kitchoi** [comment]
I agree that the ImportWarning is noisy for the scenarios where ArrayEditor is not needed.

The option to create a stub that warn or raise on first use is similar to this issue on Pyface: https://github.com/enthought/pyface/issues/800

Currently attempt to import ArrayEditor in an environment that does not have NumPy will result in a warning and an import error:
```
/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/traitsui/editors/api.py:14: ImportWarning: ArrayEditor is not available due to missing numpy
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ArrayEditor' from 'traitsui.api' (/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/traitsui/api.py)
```
It contains two parts: The ImportWarning described in this issue, and the ImportError because ArrayEditor would not be defined then.

Attempt to import `traitsui.editors.array_editor.ArrayEditor` will result in an ImportError too:
```
>>> from traitsui.editors.array_editor import ArrayEditor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
  File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/traitsui/editors/array_editor.py", line 23, in <module>
  File "/Users/kchoi/Work/ETS/py39-venv/traits-env/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 146, in _import
ModuleNotFoundError: No module named 'numpy'
```

So all in all, we fail early, which is good.

The tradeoff here are between (1) aids for debugging when you do want to use ArrayEditor but your environment does not NumPy, (2) don't bother those who don't care about ArrayEditor, (3) failing early instead of failing late.

Another alternative is to log at debug level (by default hidden) instead of warning.

**Comment by mdickinson** [comment]
Yes, just the `ImportError` may be enough here.

But the warning, in my mind, is a clear bug and definitely needs to go - we shouldn't be warning about things that the user has no reasonable way to fix, and we shouldn't expect that a user who doesn't actually need NumPy installs NumPy just to suppress the warning.
