### ISSUE TITLE
Test output: "Called attribute on invalid object:  nnnnnnnnnn" 

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#739]
When running the TraitsUI test suite using nose, I see a bunch of messages of the form: "Called attribute on invalid object:  2147484350"

This was in an EDM environment with the latest ETS releases along with Traits 6.0.0rc0. I haven't tried with the most recent Traits release instead.

Here's the top of the test output:
```
(t6-testing)bash-3.2$ nosetests traitsui
........E......................................SS.SS.S...........................SSS..................................SS.............Called attribute on invalid object:  2147484350
Called attribute on invalid object:  2147484350
Called attribute on invalid object:  2147484367
Called attribute on invalid object:  2147484367
Called attribute on invalid object:  2147484389
Called attribute on invalid object:  2147484389
Called attribute on invalid object:  2147484419
Called attribute on invalid object:  2147484419
Called attribute on invalid object:  2147484440
Called attribute on invalid object:  2147484440
Called attribute on invalid object:  2147484461
Called attribute on invalid object:  2147484461
Called attribute on invalid object:  2147484491
Called attribute on invalid object:  2147484491
..............................................................S.S.S...QCoreApplication::exec: The event loop is already running
............QCoreApplication::exec: The event loop is already running
...
```

<details>
<summary>Full test output</summary>

```
(t6-testing)bash-3.2$ nosetests traitsui
........E......................................SS.SS.S...........................SSS..................................SS.............Called attribute on invalid object:  2147484350
Called attribute on invalid object:  2147484350
Called attribute on invalid object:  2147484367
Called attribute on invalid object:  2147484367
Called attribute on invalid object:  2147484389
Called attribute on invalid object:  2147484389
Called attribute on invalid object:  2147484419
Called attribute on invalid object:  2147484419
Called attribute on invalid object:  2147484440
Called attribute on invalid object:  2147484440
Called attribute on invalid object:  2147484461
Called attribute on invalid object:  2147484461
Called attribute on invalid object:  2147484491
Called attribute on invalid object:  2147484491
..............................................................S.S.S...QCoreApplication::exec: The event loop is already running
............QCoreApplication::exec: The event loop is already running
...
======================================================================
ERROR: Failure: RuntimeError (Importing from wx backend after selecting qt4 backend!)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/site-packages/nose/loader.py", line 419, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/site-packages/traitsui/wx/__init__.py", line 27, in <module>
    from . import toolkit
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/site-packages/traitsui/wx/toolkit.py", line 29, in <module>
    assert_toolkit_import(['wx'])
  File "/Users/mdickinson/.edm/envs/t6-testing/lib/python3.6/site-packages/traitsui/toolkit.py", line 44, in assert_toolkit_import
    "backend!" % (names[0], ETSConfig.toolkit))
RuntimeError: Importing from wx backend after selecting qt4 backend!

----------------------------------------------------------------------
Ran 218 tests in 11.161s

FAILED (SKIP=13, errors=1)
```

</details>

EDM contents: (note that the Traits 5.2.0-1 entry is a lie: I've pip installed Traits 6.0.0rc0).

<details>
<summary>EDM environment contents</summary>

```
(t6-testing)bash-3.2$ edm list
# Packages in environment 't6-testing'
#  prefix: '/Users/mdickinson/.edm/envs/t6-testing'
appdirs            1.4.3-1     enthought/free
apptools           4.5.0-2     enthought/free
chaco              4.8.0-3     enthought/free
configobj          5.0.6-3     enthought/free
curl               7.58.0-1    enthought/free
distribute_remove  1.0.0-4     enthought/free
enable             4.8.1-2     enthought/free
envisage           4.9.0-1     enthought/free
fonttools          3.29.1-1    enthought/free
freetype           2.10.0-4    enthought/free
harfbuzz           2.6.4-2     enthought/free
hdf5               1.10.5-6    enthought/free
icu4c              50.2-2      enthought/free
kiwisolver         1.0.1-1     enthought/free
lib_netcdf4        4.3.3.1-11  enthought/free
libjpeg            7.0-5       enthought/free
liblzma            5.2.4-2     enthought/free
libopenjpeg        2.3.0-2     enthought/free
libpng             1.6.36-3    enthought/free
libtiff            4.0.10-5    enthought/free
libxml2            2.9.7-1     enthought/free
mayavi             4.7.1-7     enthought/free
mkl                2018.0.3-2  enthought/free
nose               1.3.7-3     enthought/free
numpy              1.17.4-1    enthought/free
packaging          16.8-3      enthought/free
pandas             0.24.2-4    enthought/free
pillow             5.2.0-4     enthought/free
pip                18.1-1      enthought/free
pyface             6.1.2-4     enthought/free
pygments           2.2.0-1     enthought/free
pyparsing          2.2.0-1     enthought/free
pyqt5              5.7.1-2     enthought/free
python_dateutil    2.8.0-2     enthought/free
pytz               2018.9-1    enthought/free
qt                 5.6.2-4     enthought/free
setuptools         41.6.0-3    enthought/free
sip                4.19.2-2    enthought/free
six                1.11.0-1    enthought/free
traits             5.2.0-1     enthought/free
traitsui           6.1.3-4     enthought/free
vtk                8.1.2-2     enthought/free
```

</details>

**Comment by mdickinson** [comment]
The messages all seem to be coming from a single test:
```
test_metadata (traitsui.tests.test_context_value.TestContextvalue) ... ok
traitsui.tests.test_controller.test_construction ... ok
test_chained_object (traitsui.tests.test_editor.TestEditor) ... Called attribute on invalid object:  2147484361
Called attribute on invalid object:  2147484361
Called attribute on invalid object:  2147484378
Called attribute on invalid object:  2147484378
Called attribute on invalid object:  2147484400
Called attribute on invalid object:  2147484400
Called attribute on invalid object:  2147484430
Called attribute on invalid object:  2147484430
Called attribute on invalid object:  2147484451
Called attribute on invalid object:  2147484451
Called attribute on invalid object:  2147484472
Called attribute on invalid object:  2147484472
Called attribute on invalid object:  2147484502
Called attribute on invalid object:  2147484502
ok
test_context_object (traitsui.tests.test_editor.TestEditor) ... ok
test_event_trait (traitsui.tests.test_editor.TestEditor) ... ok
```

**Comment by kitchoi** [comment]
The messages are no longer printed to the console. I am unable to track down which PR fixes this, though.

**Comment by mdickinson** [comment]
I'm not seeing them any more, either; a `git bisect` could likely track down the PR that fixed it, but that's probably unnecessary. Feel free to close.

**Comment by kitchoi** [comment]
Thanks. Closing.
