### ISSUE TITLE
NotImplementedError: the 'null' toolkit does not implement this method.

### ISSUE THREAD

**Issue by 625781186** [enthought/traitsui#742]
ENV:
python 3.8

other:
![image](https://user-images.githubusercontent.com/30521429/74771077-80704680-52c8-11ea-9892-f495957a84b2.png)

ERROR:
![image](https://user-images.githubusercontent.com/30521429/74771204-aa296d80-52c8-11ea-9a8f-76e370b2257c.png)

Any examples in the examples directory will not run successfully

**Comment by corranwebster** [comment]
We're not running CI against 3.8 yet, so this could be a bug.

To help rule out issues with the toolkit selection mechanism, can you please try re-running with the following line as the _first_ lines of the module:
```
from traits.etsconfig.api import ETSConfig
ETSConfig.toolkit = 'qt4'
```
(or alternatively setting the `ETS_TOOLKIT` environment variabl to `qt4`).  And yes it's `qt4` for historical reasons even though you are using Qt5.

**Comment by corranwebster** [comment]
Hmmm... also it looks like you are missing some dependencies like pygments.

**Comment by rkern** [comment]
FWIW, I get the issue on 3.6. I need both `QT_API=pyqt5 ETS_TOOLKIT=qt4` to get a UI up.

```
~/scratch 19s
❯ cat simplest_ui.py
from traits.api import HasTraits, Int

class A(HasTraits):
    x = Int()

a = A()
a.configure_traits()

~/scratch
❯ QT_API= ETS_TOOLKIT= python simplest_ui.py
Traceback (most recent call last):
  File "simplest_ui.py", line 7, in <module>
    a.configure_traits()
  File "/home/rkern/.edm/envs/python3/lib/python3.6/site-packages/traits/has_traits.py", line 2351, in configure_traits
    args,
  File "/home/rkern/.edm/envs/python3/lib/python3.6/site-packages/traitsui/toolkit.py", line 226, in view_application
    not_implemented_message.format(ETSConfig.toolkit))
NotImplementedError: the 'null' toolkit does not implement this method

~/scratch
❯ python --version
Python 3.6.0 -- Enthought, Inc. (x86_64)
```

**Comment by corranwebster** [comment]
Traits 6?

**Comment by 625781186** [comment]
> We're not running CI against 3.8 yet, so this could be a bug.
> 
> To help rule out issues with the toolkit selection mechanism, can you please try re-running with the following line as the _first_ lines of the module:
> 
> ```
> from traits.etsconfig.api import ETSConfig
> ETSConfig.toolkit = 'qt4'
> ```
> 
> (or alternatively setting the `ETS_TOOLKIT` environment variabl to `qt4`). And yes it's `qt4` for historical reasons even though you are using Qt5.

New error :

![image](https://user-images.githubusercontent.com/30521429/74772589-40f72980-52cb-11ea-8446-902a71b48768.png)

**Comment by 625781186** [comment]
> ETS_TOOLKIT=qt4

![image](https://user-images.githubusercontent.com/30521429/74773032-0fcb2900-52cc-11ea-9c1e-5d6fe6c2e255.png)

```python
Traceback (most recent call last):
  File "D:/CodePro/py_c/_Envs/m4/TraitsLearning/demo/001.py", line 5, in <module>
    from traitsui.api import *
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\api.py", line 36, in <module>
    from .editors.api import ArrayEditor
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\editors\__init__.py", line 23, in <module>
    from .api import ArrayEditor
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\editors\api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\editors\code_editor.py", line 37, in <module>
    class ToolkitEditorFactory(EditorFactory):
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\editors\code_editor.py", line 49, in ToolkitEditorFactory
    mark_color = Color(0xECE9D8)
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traits\trait_factory.py", line 40, in __call__
    return self.maker_function(*args, **metadata)
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traits\traits.py", line 717, in Color
    return ColorTrait(*args, **metadata)
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\toolkit_traits.py", line 8, in ColorTrait
    return toolkit().color_trait(*args, **traits)
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\toolkit.py", line 109, in toolkit
    _toolkit = find_toolkit('traitsui.toolkits')
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\pyface\base_toolkit.py", line 263, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\pyface\base_toolkit.py", line 217, in import_toolkit
    toolkit_object = plugin.load()
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\pkg_resources\__init__.py", line 2445, in load
    return self.resolve()
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\pkg_resources\__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\qt4\__init__.py", line 26, in <module>
    from . import toolkit
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\traitsui\qt4\toolkit.py", line 27, in <module>
    from pyface.toolkit import toolkit_object as pyface_toolkit
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\pyface\toolkit.py", line 27, in <module>
    toolkit = toolkit_object = find_toolkit('pyface.toolkits')
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\pyface\base_toolkit.py", line 263, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "D:\CodePro\py_c\_Envs\py38-32\lib\site-packages\pyface\base_toolkit.py", line 227, in import_toolkit
    raise RuntimeError(msg)
RuntimeError: No pyface.toolkits plugin could be loaded for qt4
```

**Comment by corranwebster** [comment]
Hmmm... that's odd.  You ahve `QT_API` set appropriately, so it isn't that.

What happens when you do
```
import pyface.qt
```
in that environment?

**Comment by rkern** [comment]
You'll also need `QT_API=pyqt5`, otherwise, it's looking for PyQt4.

@corranwebster Here are my packages:
```
>>> traits.__version__
'5.2.0'
>>> traitsui.__version__
'6.1.3'
>>> pyface.__version__
'6.1.2'
```

**Comment by rkern** [comment]
There also could be other import errors that our backend lookup mechanism is catching and silencing. Checking `import pyface.qt` directly is a start.

**Comment by 625781186** [comment]
> Hmmm... that's odd. ~You ahve `QT_API` set appropriately, so it isn't that.~ Edit: Robert has it below.
> 
> What happens when you do
> 
> ```
> import pyface.qt
> ```
> 
> in that environment?

![image](https://user-images.githubusercontent.com/30521429/74774159-28d4d980-52ce-11ea-91a2-ed8224fb0ba8.png)

Just a moment. Let me try pyqt5.10 instead.
Pyqt5.12 has been followed by all sorts of strange problems.

**Comment by 625781186** [comment]
> There also could be other import errors that our backend lookup mechanism is catching and silencing. Checking `import pyface.qt` directly is a start.

We should use `pyqt5==5.10.1` . 
I use python 3.6 32bit and pyqt5 5.10.1 run success. 
Pyqt changed a few things after 5.12, so sometimes I fail with pyinstaler.

**Comment by corranwebster** [comment]
Thanks, it seems like at least one thing to be done is to get CI running without the environment variables set at least sometimes.

**Comment by 625781186** [comment]
@corranwebster 
I test `pyqt5.14.1` also success . 
So it just seems unfriendly to `pyqt5.12`.

**Comment by ling-jqa** [comment]
Thanks! It actually is the promblem of the version of QT. 
![image](https://github.com/enthought/traitsui/assets/122214690/4f5bcc23-2105-404a-8824-8190756812ff)
