### ISSUE TITLE
Cannot explicitly set TupleEditor as the editor for a ValidatedTuple

### ISSUE THREAD

**Issue by mayankmanj** [enthought/traitsui#746]
Setting the argument `editor=TupleEditor()` for a `traits.api.ValidatedTuple` in a view, throws an error. Here is the minimal reproducible example:
```
from traits.api import HasTraits, Int, ValidatedTuple
from traitsui.api import Item, TupleEditor, View


class MyTrait(HasTraits):
    a = ValidatedTuple(Int(0), Int(1), fvalidate=lambda x: x[0] < x[1])

    traits_view = View(Item('a', editor=TupleEditor()))


if __name__ == "__main__":
    my_trait = MyTrait()
    my_trait.configure_traits()
```
The error is due to the facts that `ValidatedTuple` is derived from `BaseTuple`, not `Tuple`, and that the `types` attribute of the `TupleEditor` factory is not set. See --
https://github.com/enthought/traitsui/blob/18b92cf73ebce4436d98aba1f16b1132bff4c7af/traitsui/editors/tuple_editor.py#L155-L158

**Comment by mayankmanj** [comment]
Here is the full traceback:
```
Traceback (most recent call last):
  File "/home/mmanjrekar/Enthought/temp.py", line 13, in <module>
    my_trait.configure_traits()
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traits/has_traits.py", line 2088, in configure_traits
    args,
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 224, in view_application
    id, scrollable, args)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 85, in view_application
    scrollable, args).ui.result
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/view_application.py", line 128, in __init__
    args=self.args)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/view.py", line 446, in ui
    ui.ui(parent, kind)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/ui.py", line 244, in ui
    self.rebuild(self, parent)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 166, in ui_live
    ui_live.ui_live(ui, parent)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 41, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 63, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/ui_base.py", line 278, in display_ui
    ui.owner.init(ui, parent, style)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 203, in init
    self.add_contents(panel(ui), bbox)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 265, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 605, in __init__
    layout = self._add_items(content, inner)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 876, in _add_items
    editor.prepare(inner)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/editor.py", line 170, in prepare
    self.init(parent)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/editors/tuple_editor.py", line 96, in init
    self._ts = ts = TupleStructure(self)
  File "/home/mmanjrekar/.edm/envs/test/lib/python3.6/site-packages/traitsui/editors/tuple_editor.py", line 206, in __init__
    enter_set=enter_set))
TypeError: 'NoneType' object is not callable
```

**Comment by corranwebster** [comment]
Seems like the fix should just be a matter of replacing `Tuple` with `BaseTuple` in line 157.
