### ISSUE TITLE
Wx Event Handler clean-up issues

### ISSUE THREAD

**Issue by corranwebster** [enthought/traitsui#752]
There are issues with the wxPython 4 backend where event handlers are not being cleaned up correctly.  It appears that all of the event handlers explicitly added by TraitsUI are being dealt with appropriately, but there appear to be some others which are internal to wxPython with aren't being cleaned up:

- scrollbars and some base Window objects seem to have an `EvtHandler` associated with them which needs to be cleaned up.
- the Html widget appears to have an `EvtHandler` associated with it that causes an error if it _is_ cleaned up.

This is easy to hack a fix for, but I suspect a deeper problem with finalization.

**Comment by pbrod** [comment]
I have found that the call "control.FindWindowByName(name)" many times returns the wrong window/button in the tests. Then the wrong window/button is attempted disposed which often result in errors.  To find the correct window one must replace the call it with "control.FindWindowByName(name, control)".

Also to unbind correctly one must replace:
control.Unbind(wx.EVT_XXX, handler)" with "control.Unbind(wx.EVT_XXX, handler=handler)"

**Comment by kitchoi** [comment]
Quite a number of editors call `Bind` but do not unbind the event handlers in their `dispose` methods, e.g. this:
https://github.com/enthought/traitsui/blob/64858b8c9ce9189a8c9cfde60610e4bd12f30962/traitsui/wx/editor_factory.py#L115-L116

This potentially causes some test interactions that we are seeing.
@corranwebster Are these missing `Unbind` part of this issue? Or should they be separate?

**Comment by kitchoi** [comment]
> This potentially causes some test interactions that we are seeing.

For example: https://github.com/enthought/traitsui/issues/851

**Comment by ievacerny** [comment]
`ListStrEditor` is suffering from this. It seems to be unbinding everything that it binds within TraitsUI but the error is still raised when closing this basic example UI:
```
class Foo(HasTraits):
    values = List(Str)
    view = View(Item('values', editor=ListStrEditor()))

demo = Foo(values=["one", "two", "three"])
demo.configure_traits()
```
```
Event loop failed to close cleanly:
Traceback (most recent call last):
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/view_application.py", line 139, in __init__
    start_event_loop_wx(self)
  File "/Users/icernyte/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/util/guisupport.py", line 115, in st
art_event_loop_wx
    app.MainLoop()
  File "/Users/icernyte/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/wx/core.py", line 2224, in MainLoop
    rv = wx.PyApp.MainLoop(self)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py36/build/
ext/wxWidgets/src/common/wincmn.cpp(475) in ~wxWindowBase(): any pushed event handlers must have been removed
```
The issue is also causing test interactions - because the editor doesn't clean up properly, tests of `ListStrEditor` GUI fail after the first one.

**Comment by ievacerny** [comment]
Reporting another editor suffering from the same issue when closing basic example UI - `TabularEditor`

**Comment by ievacerny** [comment]
Reporting more editors that suffer from the same issue when closing UI (found by testing demos in `Standard_Editors`):
- `CodeEditor`
- `DirectoryEditor`
- `FileEditor`
- `HTMLEditor`

**Comment by ievacerny** [comment]
With wx demo application, clicking on any demo throws the following error:
```
Wx control <traitsui.wx.helper.TraitsUIPanel object at 0x12103cc18> not destroyed cleanly
Traceback (most recent call last):
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/toolkit.py", line 434, in destroy_control
    control.Destroy()
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/helper.py", line 323, in Destroy
    super().Destroy()
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed
```
