### ISSUE TITLE
Error running tests: RuntimeError: Importing from wx backend after selecting qt4 backend!

### ISSUE THREAD

**Issue by opoplawski** [enthought/traitsui#811]
Trying to run tests for 7.0.0  on Fedora rawhide with:
```
+ PYTHONPATH=/home/orion/rpmbuild/BUILDROOT/python-traitsui-7.0.0-1.fc33.x86_64/usr/lib/python3.8/site-packages
+ xvfb-run /usr/bin/python3 -s -m unittest discover -v

ERROR: traitsui.wx (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: traitsui.wx
Traceback (most recent call last):
  File "/usr/lib64/python3.8/unittest/loader.py", line 470, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib64/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/orion/fedora/python-traitsui/traitsui-7.0.0/traitsui/wx/__init__.py", line 26, in <module>
    from . import toolkit
  File "/home/orion/fedora/python-traitsui/traitsui-7.0.0/traitsui/wx/toolkit.py", line 27, in <module>
    assert_toolkit_import(["wx"])
  File "/home/orion/fedora/python-traitsui/traitsui-7.0.0/traitsui/toolkit.py", line 42, in assert_toolkit_import
    raise RuntimeError(
RuntimeError: Importing from wx backend after selecting qt4 backend!
```
Is there a way to avoid this?

**Comment by corranwebster** [comment]
You need to use nose to run the tests with exclude options depending on the backend. See https://docs.google.com/presentation/d/1GG1XisXUOsfzRf4vN_RMGJmj2xStPYuqeq75J2qPkeo/edit?usp=sharing for how we run the tests in CI.

**Comment by kitchoi** [comment]
#809 and #810 are working towards switching to using unittest (i.e. saying goodbye to 👃 ), and I think the backend exclusion is done in the test discovery there as well.

**Comment by opoplawski** [comment]
Ah, maybe I've gotten ahead of myself switching to unittest for testing traitsui.  I'll stick to nose for now since for whatever reason it doesn't fail for me.
