### ISSUE TITLE
wxAssertionError "GetEventHandler() == this" in individual tests

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#842]
The error is raised when trying to destroy children of `TraitsUIPanel` in custom `EnumEditor.rebuild_editor` and `CheckListEditor.rebuild_editor`. No error is raised if `DestroyChildren` is called when there are no children. Example traceback:
```
Traceback (most recent call last):
  File "/Users/icernyte/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traits/trait_notifiers.py", line 578, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/Users/icernyte/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/traits/trait_notifiers.py", line 682, in dispatch
    handler(*args)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/enum_editor.py", line 130, in _values_changed
    self.rebuild_editor()
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/enum_editor.py", line 368, in rebuild_editor
    panel.DestroyChildren()
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/wincmn.cpp(475) in ~wxWindowBase(): any pushed event handlers must have b
een removed
```
It might be related that same error is raised in `DataFrameEditor` tests when attempting to destroy the `TraitsUIPanel` itself:
```
Traceback (most recent call last):
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/toolkit.py", line 434, in destroy_control
    control.Destroy()
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/helper.py", line 358, in Destroy
    super().Destroy()
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/wincmn.cpp(475) in ~wxWindowBase(): any pushed event handlers must have b
een removed
```
There might be similar issues with other editors that use `TraitsUIPanel` but most of them don't have any tests or avoid the scenarios that cause issues (e.g. `SetEditor` doesn't call `DestroyChildren`)

**Comment by ievacerny** [comment]
While working on another issue I ended up tracking down why this error is being raised on destruction.

In `UI.prepare_ui` a toolkit method `hook_events` is called that attaches additional event handlers to all controls in the hierarchy. `Destroy()` methods of the underlying control objects aren't aware of these events and thus don't do the cleanup themselves. To destroy any control or control children we need to either use `destroy_control` or `destroy_children` toolkit methods, or manually call `_popEventHandlers` (in `wx/toolkit.py`) before calling `Destroy()` or `DestroyChildren()`.

**Comment by kitchoi** [comment]
This issue and the discussions referenced there might be relevant: https://github.com/wxWidgets/Phoenix/issues/627
