### ISSUE TITLE
Unable to import traitsui.wx.table_editor

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#863]
Currently importing `traitsui.wx.table_editor` emits the following errors:
```
>>> import traitsui.wx.table_editor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/wx/table_editor.py", line 35, in <module>
    from pyface.ui.wx.grid.api import Grid
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/api.py", line 21, in <module>
    from .trait_grid_model import TraitGridModel, TraitGridColumn, \
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/trait_grid_model.py", line 28, in <module>
    from .trait_grid_cell_adapter import TraitGridCellAdapter
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/trait_grid_cell_adapter.py", line 22, in <module>
    from combobox_focus_handler import ComboboxFocusHandler
ModuleNotFoundError: No module named 'combobox_focus_handler'
```
This issue probably needs an associated issue on pyface and likely be fixed in pyface too.

This is causing wx TableEditor (and their tests) to fail in obscure ways because the `traitsui.wx.editor_factory.SimpleEditor` is used as a fallback.

**Comment by kitchoi** [comment]
Closing. Sorry for the noise. I was running the tests against a rather out-of-date version of pyface. :(
