### ISSUE TITLE
TabularEditor crashes when reducing number of columns in adapter

### ISSUE THREAD

**Issue by FedeMiorelli** [enthought/traitsui#894]
I have a custom TabularAdapter that changes dynamically the number of columns in a TabularEditor based on the size of the underlying variable.

When I reduce the number of columns, I get this crash:

```
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.8.3.0\python-3.8.3.amd64\lib\site-packages\traitsui\qt4\tabular_editor.py", line 913, in columnResized
    self.resizeColumnsToContents()
  File "C:\WinPython-64bit-3.8.3.0\python-3.8.3.amd64\lib\site-packages\traitsui\qt4\tabular_editor.py", line 894, in resizeColumnsToContents
    widths = compute_column_widths(
  File "C:\WinPython-64bit-3.8.3.0\python-3.8.3.amd64\lib\site-packages\traitsui\helper.py", line 168, in compute_column_widths
    widths[i] = user_width
IndexError: list assignment index out of range
```

It seems the issue is with the user width array which is still of the wrong size.
I am submitting a PR that fixes this by resetting the user widths when there is a mismatch in size.

**Comment by kitchoi** [comment]
Closed via #897
