### ISSUE TITLE
EnumEditor fails to launch when combining mapping values and format_func 

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#912]
The following example used to work with TraitsUI 7.0:
```
from traits.api import HasStrictTraits, List, Str
from traitsui.api import View, Item, EnumEditor

mapping = {"FLAG_YES": "Yes", "FLAG_NO": "No", "": ""}

class EnumModel(HasStrictTraits):
    value = Str()

enum_editor_factory = EnumEditor(
    values=mapping,
    format_func=lambda v: mapping[v],
    mode="list"
)

view = View(
    Item(
        "value",
        editor=enum_editor_factory,
        style="simple",
    )
)

model = EnumModel()
model.configure_traits(view=view)
```

On master it fails with the following error:
```
...
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/enum_editor.py", line 96, in init
    self.values_changed()
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/enum_editor.py", line 66, in values_changed
    self._value(), self.string_value
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/helper.py", line 76, in enum_values_changed
    data = [(strfunc(v), n) for n, v in values.items()]
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/helper.py", line 76, in <listcomp>
    data = [(strfunc(v), n) for n, v in values.items()]
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/editor.py", line 212, in string_value
    return self.format_func(value)
  File "example2.py", line 12, in <lambda>
    format_func=lambda v: mapping[v],
KeyError: 'Yes'
```

<details><summary>The longer traceback</summary>

```
Traceback (most recent call last):
  File "example2.py", line 25, in <module>
    model.configure_traits(view=view)
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-pyqt/lib/python3.6/site-packages/traits/has_traits.py", line 2088, in configure_traits
    args,
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/toolkit.py", line 232, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/view_application.py", line 84, in view_application
    context, view, kind, handler, id, scrollable, args
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/view_application.py", line 126, in __init__
    args=self.args,
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/ui.py", line 246, in ui
    self.rebuild(self, parent)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/toolkit.py", line 162, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_base.py", line 284, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_panel.py", line 601, in __init__
    layout = self._add_items(content, inner)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/ui_panel.py", line 874, in _add_items
    editor.prepare(inner)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/editor.py", line 264, in prepare
    self.init(parent)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/enum_editor.py", line 158, in init
    super(SimpleEditor, self).init(parent)
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/enum_editor.py", line 96, in init
    self.values_changed()
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/qt4/enum_editor.py", line 66, in values_changed
    self._value(), self.string_value
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/helper.py", line 76, in enum_values_changed
    data = [(strfunc(v), n) for n, v in values.items()]
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/helper.py", line 76, in <listcomp>
    data = [(strfunc(v), n) for n, v in values.items()]
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/editor.py", line 212, in string_value
    return self.format_func(value)
  File "example2.py", line 12, in <lambda>
    format_func=lambda v: mapping[v],
KeyError: 'Yes'
```

</details>

With TraitsUI 7.0, it "works" because `format_func` wasn't actually used (see #782). For example, if the `format_func` was commented out then the resulting behaviour matches the expectation. #782 is now fixed and results in the above error.

**Comment by kitchoi** [comment]
I am tempted to think this is a usage error that was allowed by the bug that `format_func` wasn't actually used. However I am wondering if there is a way to mitigate errors seen by downstream projects, something along the line of capturing this usage error, applying a workaround and then emit a warning. Then in some later release, once downstream projects have a chance to fix this usage error, remove the workaround and let the error raise.

**Comment by kitchoi** [comment]
Adding this to the 7.0.1 bug fix release milestone so that it can be evaluated together with #782.

**Comment by ievacerny** [comment]
I also think this is a usage error. Providing a dictionary to `values` automatically takes care of the mapping so there is no need for `format_func` that does the same mapping as well. As for what to do with the error, I don't know what would be the best approach here.

**Comment by kitchoi** [comment]
Offline discussion: This is a usage error that can be fixed by removing the offending and previously unused `format_func`.

Given the understanding that the error should only affect very small number of users and it can be fixed easily, we have decided not to suppress or workaround it, which will nonetheless add complexity to the library code. However if it occurs that this error cannot be easily fixed by downstream projects, e.g. there are a chain of dependencies where the error occurs in code base outside of the developers' control or that the error is blocking mission critical work, please consider reopening it.

Closing as won't fix (for now).
