### ISSUE TITLE
Unable to test with TableEditor with wx on Appveyor

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#920]
In two of the recent PRs (https://github.com/enthought/traitsui/pull/915, https://github.com/enthought/traitsui/pull/919), we started seeing this in the Appveyor build with wx:

```
======================================================================
ERROR: test_filtered_table_editor (traitsui.tests.editors.test_table_editor.TestTableEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_table_editor.py", line 288, in test_filtered_table_editor
    filter = ui.get_editors("values")[0].filter
AttributeError: 'SimpleEditor' object has no attribute 'filter'
======================================================================
ERROR: test_table_editor_select_cell (traitsui.tests.editors.test_table_editor.TestTableEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_table_editor.py", line 489, in test_table_editor_select_cell
    selected = editor.selected_cell
AttributeError: 'SimpleEditor' object has no attribute 'selected_cell'
======================================================================
ERROR: test_table_editor_select_cell_index (traitsui.tests.editors.test_table_editor.TestTableEditor)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-wx\lib\site-packages\traitsui\tests\editors\test_table_editor.py", line 542, in test_table_editor_select_cell_index
    selected = editor.selected_cell_index
AttributeError: 'SimpleEditor' object has no attribute 'selected_cell_index'
======================================================================

... (a couple similar ones)
```

The error looks like a symptom of a failure to import `traitsui.wx.table_editor` (see #864)

Unfortunately the build on Appveyor for wx is allowed to fail, which makes it harder to detect this sort of things early.

**Comment by kitchoi** [comment]
This may be the earliest commit where this started to happen: https://github.com/enthought/traitsui/pull/853/commits/717c9d3bf6928b33685ff6a6cb1ad1e0d38355b2 
Keep digging...

**Comment by kitchoi** [comment]
Got it. https://github.com/enthought/traitsui/pull/853 added test dependencies which install the release version of `pyface` from PyPI. While that would have been our goal in the future, we do need pyface master for CI. When CI script gets to `pip install -r ci-src-requirements.txt --no-dependencies` for installing pyface master, pyface is already there and master is not installed. Then when the test tries to import `traitsui.wx.table_editor`, it runs into this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/wx/table_editor.py", line 35, in <module>
    from pyface.ui.wx.grid.api import Grid
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/api.py", line 21, in <module>
    from .trait_grid_model import TraitGridModel, TraitGridColumn, \
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/trait_grid_model.py", line 28, in <module>
    from .trait_grid_cell_adapter import TraitGridCellAdapter
  File "/Users/kchoi/.edm/envs/traitsui-test-3.6-wx/lib/python3.6/site-packages/pyface/ui/wx/grid/trait_grid_cell_adapter.py", line 22, in <module>
    from combobox_focus_handler import ComboboxFocusHandler
ModuleNotFoundError: No module named 'combobox_focus_handler'
```
I think these days I have been habitually reinstate a local development installation of pyface and I could have reproduced this locally.
