### ISSUE TITLE
WxPython 4.1 DirectoryEditor and FileEditor demos won't launch due to alignment flag

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#936]
Launching `examples/demo/Standard_Editors/DirectoryEditor_demo.py` and `examples/demo/Standard_Editors/FileEditor_demo.py` using wx (4.1.0) toolkit fails with the following error:
```
Traceback (most recent call last):
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/view_application.py", line 152, in OnInit
    args=self.args,
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/ui.py", line 246, in ui
    self.rebuild(self, parent)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/toolkit.py", line 125, in ui_live
    ui_live.ui_live(ui, parent)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_live.py", line 52, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_live.py", line 88, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_base.py", line 71, in display_ui
    ui.owner.init(ui, parent, style)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_live.py", line 203, in init
    sw = panel(ui, window)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 272, in panel
    panel, content[0], ui
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 431, in fill_panel_for_group
    panel, group, ui, suppress_label, is_dock_window, create_panel
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 587, in __init__
    self.add_items(content, panel, self.sizer)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 908, in add_items
    editor.prepare(item_panel)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/editor.py", line 264, in prepare
    self.init(parent)
  File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/file_editor.py", line 96, in init
    sizer.Add(control, 1, wx.EXPAND | wx.ALIGN_CENTER)
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_BOTTOM | wxALIGN_CENTRE_VERTICAL))" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/common/sizer.cpp(2114) in DoInsert(): Vertical alignment flags are ignored with wxEXPAND
```

**Comment by ievacerny** [comment]
Duplicate of #889. Sorry for the noise.
