### ISSUE TITLE
process cascade events occasional failure with PyQt and Appveyor

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#951]
The following failure occurs a few times on [#932](https://github.com/enthought/traitsui/pull/932) but it looks obviously unrelated:
```
======================================================================
FAIL: test_qt_process_events_process_all (traitsui.tests.test__tools.TestProcessEventsRepeated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-pyside2\lib\site-packages\traitsui\tests\test__tools.py", line 113, in test_qt_process_events_process_all
    self.assertEqual(q_object.n_events, max_n_events)
AssertionError: 2 != 10
```

It is not reproducible on an actual Windows machine.

**Comment by kitchoi** [comment]
It is weird that we are seeing more of this lately, we got another one from: https://github.com/enthought/traitsui/pull/955

**Comment by kitchoi** [comment]
One with [PyQt5](https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/33875471/job/2qahd9ewmfo8odrs), so it is not just PySide2.

**Comment by kitchoi** [comment]
This is the first one I have seen a different error message where the actual number of events wasn't `2`, but this was with [PyQt4 and a Travis CI build on OSX](https://travis-ci.org/github/enthought/traitsui/jobs/705719573):
```
======================================================================
FAIL: test_qt_process_events_process_all (traitsui.tests.test__tools.TestProcessEventsRepeated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/.edm/envs/traitsui-test-3.6-pyqt/lib/python3.6/site-packages/traitsui/tests/test__tools.py", line 110, in test_qt_process_events_process_all
    self.assertEqual(q_object.n_events, 1)
AssertionError: 3 != 1
```
(Note that this is on #971, and "pyqt" means PyQt4)

**Comment by kitchoi** [comment]
Turns out this test failure is very reproducible with PyQt4 and Mac OSX! (Discovered via #971)

**Comment by kitchoi** [comment]
For reference, if I install Qt 4.8.7, and change `process_cascade_events` to this instead:
```
        from pyface.qt import QtCore
        event_loop = QtCore.QEventLoop(QtCore.QCoreApplication.instance())
        for _ in range(20):
            result = event_loop.processEvents(QtCore.QEventLoop.AllEvents)
            print(result)
```
All the printed `result` is `False` when I run the test on Mac OSX  (20 is larger than the number of cascades expected in the tests). But the test still passes because the events are processed.

Whereas if I install Qt 5, then run the test, I get the correct number of `True`, i.e. the number of `True` printed is consistent with the number of cascade I expected.

This might indicate the cause to the problem: `QCoreApplication.processEvents(flags, max_time)` essentially wraps `QEventLoop.processEvents` with a timer. As it loops, it relies on the returned value indicating whether it has just processed some events, and if it has processed, call `QEventLoop.processEvents` again. See this [source](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/kernel/qcoreapplication.cpp?id=56410a51cc897e3b38a0794019ebf196b1eb22d5#n1316).

So to translate that to Python, this is essentially what the function should have:
```
        from pyface.qt import QtCore
        event_loop = QtCore.QEventLoop(QtCore.QCoreApplication.instance())
        while event_loop.processEvents(QtCore.QEventLoop.AllEvents):
            pass
```

If I changed the function to the above block and run it against Qt 4.8 (on Mac OSX), I get this error very consistently:
```
======================================================================
FAIL: test_qt_process_events_process_all (traitsui.tests.test__tools.TestProcessEventsRepeated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kchoi/Work/ETS/traitsui/traitsui/tests/test__tools.py", line 116, in test_qt_process_events_process_all
    self.assertEqual(q_object.n_events, max_n_events)
AssertionError: 4 != 10
```

Interestingly, if I run the first code snippet (containing `QEventLoop.prcessEvents` and `print(result)`) with Qt 4.8 on Windows, the test does not fail and I got the correct number of `True` values being printed, consistent with the number of cascade expected. So this is a very Qt-version-and-platform-specific behaviour.

**Comment by kitchoi** [comment]
The function has been rewritten in #975, and the test error message has been expanded in #973. The test is skipped on Qt4 + OSX now because the buggy behaviour is fairly consistent there.  It has not failed once for Qt5 + OSX, and it has not failed on Linux builds so far.

On Appveyor, now we _occasionally_ see this failure on Qt5 (for example, this [build](https://ci.appveyor.com/project/EnthoughtOSS/traitsui/builds/34092577/job/5j9alfqb48fy3l1m)):
```
======================================================================
FAIL: test_qt_process_events_process_all (traitsui.tests.test__tools.TestProcessEventsRepeated)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\appveyor\.edm\envs\traitsui-test-3.6-pyqt5\lib\site-packages\traitsui\tests\test__tools.py", line 145, in test_qt_process_events_process_all
    self.assertEqual(n_left_behind_events, 0, msg)
AssertionError: 8 != 0 : Expected 10 events processed on the objects and zero events left on the queue after running process_cascade_events. Found 2 processed with 8 left behind.
```
It is the same error as the original one, it is just the failure message is now expanded to provide more information.

With that, we can confirm the symptom on Appveyor is similar to that with Qt4 + OSX:
- Some events are processed, but not all.
- If the test does fail, the number of events processed (and unprocessed) is always the same for a given platform. Across platforms, the value is different.

Since I am not able to reproduce this on my Windows machine (not once!), I could only guess that what happens on Appveyor with Qt5 is probably similar to what happened with Qt4 + OSX: The `QEventLoop.processEvents` does process some events but still reports it hasn't, causing the loop to break too early.

Qt dependencies on Appveyor on which the error was observed:
```
    pyqt5            5.14.2-3
    pyqt5_sip        12.7.2-1
    qt               5.12.6-5
```
