### ISSUE TITLE
DateEditor and DateRangeEditor issues

### ISSUE THREAD

**Issue by ievacerny** [enthought/traitsui#962]
Issues found by testing `Date_editor_demo.py` and `Date_range_editor_demo.py` in `examples/demos/Advanced` on MacOS.

- [ ] 1. Qt simple style `DateEditor` shows the date "01/01/2000" when the underlying trait value is `None`. All other editor styles and wx simple style implementation show the current date.

- [ ] 2. Wx `DateEditor` feels broken from UX perspective. With every click on a day in the calendar the following error is thrown (both wx 4.0 and wx 4.1):
  ```
  wx._core.wxAssertionError: C++ assertion "retval != __null" failed at /Users/robind/projects/bb2/dist-osx-py36/build/ext/wxWidgets/src/osx/carbon/graphics.cpp(141) in wxMacCreateCGColor():

  The above exception was the direct cause of the following exception:

  SystemError: <class 'wx._core.PaintEvent'> returned a result with an error set
  ```

- [ ] 3. Qt `DateEditor` also feels broken from UX perspective, but the issue seems to be not frequent enough updates. The issue is seen with `PySide2           5.11.0`, `PyQt5             5.14.2; PyQt5-sip         12.7.2; Qt                5.12.6` but not with `PyQt              4.11.4; Qt                4.8.7`.

- [ ] 4. `DateRangeEditor` is not implemented in wx, but rather than giving an informative error message it attempts to use `DateEditor` and the  `Date_range_editor_demo.py` fails with the following error:
  ```
  Traceback (most recent call last):
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/view_application.py", line 152, in OnInit
      args=self.args,
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/view.py", line 462, in ui
      ui.ui(parent, kind)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/ui.py", line 246, in ui
      self.rebuild(self, parent)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/toolkit.py", line 125, in ui_live
      ui_live.ui_live(ui, parent)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_live.py", line 52, in ui_live
      _ui_dialog(ui, parent, BaseDialog.NONMODAL)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_live.py", line 88, in _ui_dialog
      BaseDialog.display_ui(ui, parent, style)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_base.py", line 71, in display_ui
      ui.owner.init(ui, parent, style)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_live.py", line 203, in init
      sw = panel(ui, window)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 272, in panel
      panel, content[0], ui
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 431, in fill_panel_for_group
      panel, group, ui, suppress_label, is_dock_window, create_panel
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 587, in __init__
      self.add_items(content, panel, self.sizer)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/ui_panel.py", line 908, in add_items
      editor.prepare(item_panel)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/editor.py", line 264, in prepare
      self.init(parent)
    File "/Users/icernyte/Documents/repos/traitsui/traitsui/wx/date_editor.py", line 829, in init
      raise ValueError("Multi-select is True, but editing a non-list.")
  ValueError: Multi-select is True, but editing a non-list.
  ```

**Comment by kitchoi** [comment]
> Qt DateEditor also feels broken from UX perspective, but the issue seems to be not frequent enough updates. The issue is seen with PySide2 5.11.0, PyQt5 5.14.2; PyQt5-sip 12.7.2; Qt 5.12.6 but not with PyQt 4.11.4; Qt 4.8.7

Could you be a bit more specific please? I just tried the `Date_editor_demo.py` example with Mac OSX and PyQt5 and I am not sure I understand the "feel broken" part of the issue... maybe I have not tested the right thing?

**Comment by ievacerny** [comment]
> > Qt DateEditor also feels broken from UX perspective, but the issue seems to be not frequent enough updates. The issue is seen with PySide2 5.11.0, PyQt5 5.14.2; PyQt5-sip 12.7.2; Qt 5.12.6 but not with PyQt 4.11.4; Qt 4.8.7
> 
> Could you be a bit more specific please? I just tried the `Date_editor_demo.py` example with Mac OSX and PyQt5 and I am not sure I understand the "feel broken" part of the issue... maybe I have not tested the right thing?

Updated the original issue comment.

**Comment by kitchoi** [comment]
> Switching between the months doesn't update the days. They are updated one by one after clicking on them.

I see. You meant clicking the left and right buttons for switching the months?  I think switching a month using the drop down works. It is only about the calendar view not being updated to the new month, not about the trait values being updated, right?

**Comment by ievacerny** [comment]
> > Switching between the months doesn't update the days. They are updated one by one after clicking on them.
> 
> I see. You meant clicking the left and right buttons for switching the months? I think switching a month using the drop down works. It is only about the calendar view not being updated to the new month, not about the trait values being updated, right?

Yes, using left and right UI buttons. And yes, it's only a cosmetic issue, the view isn't updated often enough.

**Comment by kitchoi** [comment]
I just tested this with a Linux machine using PyQt 5.14, and the view is updating as expected.  The above issue with the DateEditor view is seen on Mac OSX right? This is looking similar to the issues seen in #913.  I will test with Windows...

**Comment by ievacerny** [comment]
It looks similar, but #913 doesn't affect PySide2 while this does

**Comment by kitchoi** [comment]
> I just tested this with a Linux machine using PyQt 5.14, and the view is updating as expected. The above issue with the DateEditor view is seen on Mac OSX right? This is looking similar to the issues seen in #913. I will test with Windows...

Just tested with Windows too (PyQt 5.14.2), the calendar view also updates fine... so it is getting to look mac OSX specific again.

The following code seems to reproduce the behaviour just as well:
```
from pyface.qt import QtCore, QtGui
app = QtGui.QApplication([])
control = QtGui.QMainWindow(None)
control.setVisible(True)
calendar = QtGui.QCalendarWidget(control)
control.setCentralWidget(calendar)
app.exec_()
```

**Comment by kitchoi** [comment]
For the record, somehow forcing the widget to be disabled and enabled again "fixes" it (I think this is more like a workaround):
```
try:
    from PyQt5 import QtCore
    from PyQt5.QtWidgets import *
except ImportError:
    from PySide2 import QtCore
    from PySide2.QtWidgets import *

class MyFilter(QtCore.QObject):
    def eventFilter(self, object, event):
        if event.type() == QtCore.QEvent.LayoutRequest:
            object.setEnabled(False)
            object.setEnabled(True)
        return super().eventFilter(object, event)

app = QApplication([])
control = QMainWindow(None)
control.setVisible(True)
calendar = QCalendarWidget(control)

filter_ = MyFilter()
calendar.installEventFilter(filter_)

control.setCentralWidget(calendar)
app.exec_()

```
