### ISSUE TITLE
CodeEditor not working with yaml lexer

### ISSUE THREAD

**Issue by robertopreste** [enthought/traitsui#982]
Using a `CodeEditor` with `lexer="yaml"` results in the following error, which also causes the application to crash:

```
Traceback (most recent call last):
  File "/Users/rpreste/.edm/envs/envivo/lib/python3.6/site-packages/pyface/ui/qt4/code_editor/pygments_highlighter.py", line 168, in highlightBlock
    format = self._get_format(token)
  File "/Users/rpreste/.edm/envs/envivo/lib/python3.6/site-packages/pyface/ui/qt4/code_editor/pygments_highlighter.py", line 195, in _get_format
    for key, value in self._style.style_for_token(token).items():
  File "/Users/rpreste/.edm/envs/envivo/lib/python3.6/site-packages/pygments/style.py", line 106, in style_for_token
    t = cls._styles[token]
KeyError: Token.Literal.Scalar.Plain
```

This also happens with `lexer="salt"`, which highlights yaml + Jinja syntax.

Some sample code to reproduce the issue is included here:

<details>
<summary>Sample</summary>

```python
from traits.api import Code, HasTraits
from traitsui.api import CodeEditor, Item, View


class MyCode(HasTraits):

    code = Code("version: 1")

    def default_traits_view(self):
        return View(
            Item("code", style="readonly",
                 editor=CodeEditor(lexer="yaml")),
        )


if __name__ == "__main__":
    sample = MyCode()
    sample.configure_traits()
```

</details>

**Comment by rahulporuri** [comment]
I was wondering why this wasn't closed but I guess we can't close this issue until pyface 7.0.1 is released.

**Comment by kitchoi** [comment]
Because it was on a different repository... Closing via https://github.com/enthought/pyface/pull/566

**Comment by kitchoi** [comment]
I should have come to close this manually before. Thank you for the reminder!
